(function(global){
"use strict";
 function create({root,content,getText,mutate,onDrop,onRange,onDates,onSwipe}){
  let month=content.localDateKey().slice(0,7),selectedDays=new Set(),dragId='',dragDate='',dropDate='',pointer=null,swipe=null,suppressClickUntil=0,suppressClickId='';
 const calendar=root.querySelector('#journalCalendar'),hint=root.querySelector('#dragHint');
 function renderCalendar(){const [y,m]=month.split('-').map(Number),first=new Date(y,m-1,1,12).getDay(),days=new Date(y,m,0,12).getDate(),counts=content.getMonthCounts(getText(),month);let cells='';
 for(let i=0;i<first;i++)cells+='<span></span>';
  const today=content.localDateKey();
  for(let i=1;i<=days;i++){const date=month+'-'+String(i).padStart(2,'0'),c=counts[date]||{},selected=selectedDays.has(date),weekend=[0,6].includes(new Date(y,m-1,i,12).getDay()),past=date<today,counters=[...content.PRIORITIES,"pending"].map(p=>Array.from({length:c[p]||0},()=>`<span class="calendar-dot ${p}" aria-hidden="true"></span>`).join("")).join('');cells+=`<button type="button" class="month-day ${date===today?'is-today':''} ${past?'is-past':''} ${selected?'is-selected':''} ${weekend?'weekend':''}" data-month-date="${date}" data-drop-date="${date}" aria-label="${date}，${Object.values(c).reduce((a,b)=>a+b,0)} 個 Action${past?'，過去日期':''}${selected?'，已選取':''}" aria-pressed="${selected}"><strong>${i}</strong><span class="day-counts">${counters}</span></button>`}
  calendar.innerHTML=`<div class="calendar-head"><button class="btn" data-month-step="-1" aria-label="上個月">‹</button><strong>${y} 年 ${m} 月</strong><button class="btn" data-month-step="1" aria-label="下個月">›</button></div><div class="month-grid">${['日','一','二','三','四','五','六'].map((n,index)=>`<span class="weekday ${index===0||index===6?'weekend':''}">${n}</span>`).join('')}${cells}</div>`;
  }
  function toggleDay(date){if(selectedDays.has(date))selectedDays.delete(date);else selectedDays.add(date);onDates([...selectedDays].sort())}
 function clearPreview(){root.querySelectorAll('.drop-target').forEach(n=>n.classList.remove('drop-target'));root.querySelectorAll('.drop-preview').forEach(n=>n.remove());hint.classList.add('hidden');dropDate=''}
 function scrollContainer(){const timeline=root.querySelector('.journal-timeline');return timeline&&getComputedStyle(timeline).overflowY==='auto'?timeline:document.scrollingElement}
 function scrollDrag(amount){const container=scrollContainer();if(container===document.scrollingElement)scrollBy(0,amount);else container.scrollTop+=amount}
 function beginDrag(source){dragId=source.dataset.dragId;dragDate=content.getBullet(getText(),dragId)?.date||source.closest('[data-drop-date]')?.dataset.dropDate||'';const origin=source.closest('.agenda-day'),top=origin?.getBoundingClientRect().top;source.classList.add('dragging');root.classList.add('action-drag-active');if(origin&&top!==undefined)scrollDrag(origin.getBoundingClientRect().top-top)}
 function preview(target){const zone=target?.closest('[data-drop-date]');if(!zone){clearPreview();return}const date=zone.dataset.dropDate;if(date===dropDate&&(date===dragDate||zone.classList.contains('drop-target')))return;clearPreview();dropDate=date;if(date===dragDate)return;zone.classList.add('drop-target');hint.textContent='放開移到 '+date;hint.classList.remove('hidden');
 const source=content.getBullet(getText(),dragId);if(!source)return;const section=zone.matches('.agenda-day')?zone:null;if(!section)return;
 const marker=document.createElement('div');marker.className='drop-preview';marker.textContent=source.action||source.title;const list=section.querySelector('.agenda-section .bullet-list');if(list)list.append(marker);else section.append(marker);
 }
 function finish(commit){const id=dragId,date=dropDate,changed=date&&date!==dragDate;clearPreview();root.querySelectorAll('.dragging').forEach(n=>n.classList.remove('dragging'));root.classList.remove('action-drag-active');dragId='';dragDate='';pointer=null;pointerY=null;if(commit&&id&&changed){if(onDrop)onDrop(id,date);else mutate(text=>content.updateBullet(text,id,{date}));renderCalendar()}}
  root.addEventListener('dragstart',e=>{const handle=e.target.closest('.action-drag-handle'),source=handle?.closest('[data-drag-id]');if(!source)return;e.stopPropagation();beginDrag(source);e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',dragId)});
 root.addEventListener('dragover',e=>{if(!dragId)return;e.preventDefault();e.dataTransfer.dropEffect='move';preview(e.target);if(e.clientY<80)scrollDrag(-18);if(e.clientY>innerHeight-80)scrollDrag(18)});
 root.addEventListener('drop',e=>{if(!dragId)return;e.preventDefault();preview(e.target);finish(true)});root.addEventListener('dragend',()=>finish(false));
 let pointerY=null;
 root.addEventListener('pointerdown',e=>{const handle=e.target.closest('.action-drag-handle');if(!handle||e.button!==0)return;e.preventDefault();beginDrag(handle.closest('[data-drag-id]'));pointer=e.pointerId;pointerY=e.clientY;handle.setPointerCapture(pointer)});
 root.addEventListener('pointermove',e=>{if(pointer!==e.pointerId)return;e.preventDefault();if(e.pointerType==='touch'||e.pointerType==='pen')scrollDrag(pointerY-e.clientY);pointerY=e.clientY;preview(document.elementFromPoint(e.clientX,e.clientY));if(e.clientY<80)scrollDrag(-18);if(e.clientY>innerHeight-80)scrollDrag(18)});
 root.addEventListener('pointerup',e=>{if(pointer===e.pointerId){preview(document.elementFromPoint(e.clientX,e.clientY));finish(true)}});root.addEventListener('pointercancel',()=>finish(false));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&dragId)finish(false)});
 function clearSwipe(){if(swipe?.card){swipe.card.style.removeProperty('transform');swipe.card.classList.remove('swiping-left','swiping-right')}swipe=null}
 root.addEventListener('pointerdown',e=>{const card=e.target.closest('article.bullet[data-id]');if(!card||e.target.closest('.action-drag-handle')||e.button!==0)return;swipe={card,id:card.dataset.id,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,dx:0,active:false}});
 root.addEventListener('pointermove',e=>{if(!swipe||swipe.pointerId!==e.pointerId)return;const dx=e.clientX-swipe.startX,dy=e.clientY-swipe.startY;if(!swipe.active&&Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)*1.2){swipe.active=true;try{swipe.card.setPointerCapture?.(e.pointerId)}catch{}}if(!swipe.active)return;e.preventDefault();swipe.dx=dx;const ready=Math.abs(dx)>=72;swipe.card.classList.toggle('swiping-left',ready&&dx<0);swipe.card.classList.toggle('swiping-right',ready&&dx>0);swipe.card.style.transform=`translateX(${Math.max(-96,Math.min(96,dx))}px)`});
 root.addEventListener('pointerup',e=>{if(!swipe||swipe.pointerId!==e.pointerId)return;const state=swipe,commit=state.active&&Math.abs(state.dx)>=72,direction=state.dx<0?'left':'right';if(state.active){suppressClickUntil=performance.now()+500;suppressClickId=state.id}clearSwipe();if(commit)onSwipe(state.id,direction)});root.addEventListener('pointercancel',()=>clearSwipe());
 root.addEventListener('click',e=>{const card=e.target.closest('article.bullet[data-id]');if(card?.dataset.id===suppressClickId&&performance.now()<suppressClickUntil){e.preventDefault();e.stopImmediatePropagation()}},true);
 root.addEventListener('click',e=>{if(e.target.closest('.action-drag-handle'))e.preventDefault()});
  root.addEventListener('click',e=>{const step=e.target.closest('[data-month-step]'),day=e.target.closest('[data-month-date]'),range=e.target.closest('[data-agenda-range]');if(step){const [y,m]=month.split('-').map(Number);month=content.localDateKey(new Date(y,m-1+Number(step.dataset.monthStep),1,12)).slice(0,7);renderCalendar()}if(day)toggleDay(day.dataset.monthDate);if(range){selectedDays.clear();renderCalendar();onRange(range.dataset.agendaRange)}});
  return{renderCalendar,getSelectedDates:()=>[...selectedDays].sort()};
}
global.DriveMemoJournal={create};
})(window);
