(function(global){
"use strict";
// Each editable line owns its children; persisted markup contains no editor controls.
function create(root,{sanitize,decorate,onSelectionChange=()=>{}}){
 let saved=null,multi=false;const selected=new Set(),history=[];let clipboard=null;
 function checkpoint(){const html=persisted(root.innerHTML);if(history.at(-1)!==html)history.push(html);if(history.length>100)history.shift()}
 function undo(){const html=history.pop();if(html===undefined)return;const wasMulti=multi;restore(html);if(wasMulti)toggleSelection();focus(root.firstElementChild,false)}
 function remember(){const s=getSelection();if(s?.rangeCount&&root.contains(s.anchorNode)&&root.contains(s.focusNode))saved=s.getRangeAt(0).cloneRange()}
 function current(){const n=saved?.startContainer;return(n?.nodeType===1?n:n?.parentElement)?.closest('.outline-line')?.parentElement||root.lastElementChild}
 function focus(block,end=true){const line=block.querySelector(':scope > .outline-line');root.focus({preventScroll:true});const r=document.createRange();r.selectNodeContents(line);r.collapse(!end);getSelection().removeAllRanges();getSelection().addRange(r);remember()}
 function makeNode(){const n=document.createElement('div');n.className='outline-node';Object.defineProperty(n,'open',{get(){return !this.hasAttribute('data-collapsed')},set(v){this.toggleAttribute('data-collapsed',!v)}});return n}
 function persisted(html){const t=document.createElement('div');t.innerHTML=html;for(const n of [...t.querySelectorAll('.outline-node')].reverse()){const d=document.createElement('details');if(!n.hasAttribute('data-collapsed'))d.open=true;d.append(...n.childNodes);n.replaceWith(d)}for(const n of t.querySelectorAll('.outline-line')){const line=document.createElement('summary');line.append(...n.childNodes);n.replaceWith(line)}return sanitize(t.innerHTML)}
 function block(html=''){const d=makeNode();d.open=true;const s=document.createElement('div');s.className='outline-line';s.setAttribute('role','textbox');s.setAttribute('aria-label','條列文字');s.innerHTML=html||'<br>';d.append(s);return d}
 function restore(html){selected.clear();multi=false;root.classList.remove('selecting');onSelectionChange(false,0);root.replaceChildren();const source=document.createElement('div');source.innerHTML=sanitize(html);function walk(container,target){for(const n of [...container.childNodes]){if(n.nodeType===3){if(n.textContent.trim())target.append(block(n.textContent.replace(/&/g,'&amp;').replace(/</g,'&lt;')));continue}if(n.nodeType!==1)continue;if(n.matches('details')){const summary=n.querySelector(':scope > summary'),d=block(summary?.innerHTML||'');d.open=n.hasAttribute('open');target.append(d);const kids=document.createElement('div');kids.className='outline-children';for(const child of [...n.children])if(child!==summary)walk(child,kids);if(kids.children.length)d.append(kids)}else if(n.matches('ul,ol')||n.classList.contains('outline-children')||n.classList.contains('outline-body'))walk(n,target);else if(n.matches('li')){const copy=n.cloneNode(true);copy.querySelectorAll('ul,ol').forEach(x=>x.remove());const d=block(copy.innerHTML);target.append(d);const kids=document.createElement('div');kids.className='outline-children';for(const list of n.querySelectorAll(':scope > ul,:scope > ol'))walk(list,kids);if(kids.children.length)d.append(kids)}else if(n.matches('p,div')&&n.querySelector('p,div,details,ul,ol'))walk(n,target);else if(n.textContent.trim()||n.querySelector('a')){for(const line of n.innerHTML.split(/<br\s*\/?>/i))target.append(block(line))}}}walk(source,root);if(!root.children.length)root.append(block());decorate(root);saved=null}
 function load(html){restore(html);history.length=0}
 function add(){checkpoint();remember();const at=current(),next=block();if(at)at.after(next);else root.append(next);focus(next)}
 function indent(out=false){remember();const targets=multi?selectedRoots():[current()].filter(Boolean);if(!targets.length)return;checkpoint();for(const at of out?[...targets].reverse():targets){if(out){const parent=at.parentElement.closest('.outline-node');if(parent&&root.contains(parent))parent.after(at)}else{let prev=at.previousElementSibling;while(prev&&selected.has(prev))prev=prev.previousElementSibling;if(!prev?.matches('.outline-node'))continue;let kids=prev.querySelector(':scope > .outline-children');if(!kids){kids=document.createElement('div');kids.className='outline-children';prev.append(kids)}kids.append(at);prev.open=true}}if(!multi)focus(targets[0])}
 function format(property,value){checkpoint();if(!saved||!root.contains(saved.commonAncestorContainer))return;const line=(saved.startContainer.nodeType===1?saved.startContainer:saved.startContainer.parentElement).closest('.outline-line');if(!line)return;root.focus({preventScroll:true});const r=saved.cloneRange();if(r.collapsed)r.selectNodeContents(line);if(!line.contains(r.endContainer))return;const span=document.createElement('span');span.style[property]=value;const fragment=r.extractContents();for(const node of fragment.querySelectorAll('*')){node.style[property]='';if(property==='color')node.removeAttribute('color');if(property==='fontSize')node.removeAttribute('size')}span.append(fragment);r.insertNode(span);r.selectNodeContents(span);getSelection().removeAllRanges();getSelection().addRange(r);remember()}
 function insertLink(name,url){checkpoint();const at=current()||root.lastElementChild,line=at.querySelector(':scope > .outline-line'),a=document.createElement('a');a.href=url;a.textContent=name;line.append(a);decorate(root);focus(at)}

 function selectionChanged(){root.querySelectorAll('.outline-node').forEach(n=>n.classList.toggle('outline-selected',selected.has(n)));onSelectionChange(multi,selectedRoots().length)}
 function toggleSelection(force){multi=force===undefined?!multi:Boolean(force);selected.clear();root.classList.toggle('selecting',multi);selectionChanged();return multi}
 function selectedRoots(){return [...root.querySelectorAll('.outline-node')].filter(n=>selected.has(n)&&![...selected].some(p=>p!==n&&p.contains(n)))}
 function move(delta){const list=selectedRoots();if(!list.length)return;checkpoint();const ordered=delta<0?list:[...list].reverse();for(const n of ordered){const neighbor=delta<0?n.previousElementSibling:n.nextElementSibling;if(neighbor&&!selected.has(neighbor)){if(delta<0)neighbor.before(n);else neighbor.after(n)}}list[0].scrollIntoView({block:'nearest'})}
 function expand(open){checkpoint();const targets=selectedRoots();if(!targets.length){const at=current();if(at)targets.push(at)}for(const at of targets){at.open=open;at.querySelectorAll('.outline-node').forEach(n=>n.open=open)}}
 function placeholder(name){checkpoint();const at=current(),next=block();const label=document.createElement('span');label.textContent='【Pic】';const status=document.createElement('span');status.contentEditable='false';status.className='upload-placeholder';status.textContent=' ⏳ 上傳中';next.firstChild.replaceChildren(label,status);if(at)at.after(next);else root.append(next);focus(next);return {complete(url){if(!root.contains(status))return;const line=status.closest('.outline-line');if(!line)return;status.remove();const a=document.createElement('a');a.href=url;a.textContent='【Pic】';line.replaceChildren(a);decorate(root)},fail(){if(root.contains(next))status.textContent=' ⚠ 上傳失敗，請重新插入圖片'}}}
 root.addEventListener('keydown',e=>{if(e.isComposing)return;if(e.key==='Escape'&&multi){e.preventDefault();toggleSelection(false);return}if(!['ArrowUp','ArrowDown'].includes(e.key))return;const line=(e.target.closest('.outline-line')||current()?.querySelector(':scope > .outline-line'));if(!line)return;const lines=[...root.querySelectorAll('.outline-line')].filter(n=>n.getClientRects().length),next=lines[lines.indexOf(line)+(e.key==='ArrowUp'?-1:1)];if(e.shiftKey&&innerWidth>820){e.preventDefault();if(!multi){multi=true;root.classList.add('selecting');selected.add(line.parentElement)}if(next)selected.add(next.parentElement);selectionChanged();if(next)focus(next.parentElement,e.key==='ArrowUp');return}if(e.shiftKey)return;if(next){e.preventDefault();focus(next.parentElement,e.key==='ArrowUp')}});
 root.contentEditable='true';
 root.addEventListener('beforeinput',e=>{if(e.inputType==='historyUndo'){e.preventDefault();undo();return}if(e.inputType==='insertParagraph'||e.inputType==='insertLineBreak'){e.preventDefault();splitLine();return}checkpoint()});
 root.addEventListener('keydown',async e=>{if(!(e.ctrlKey||e.metaKey)||e.shiftKey)return;const key=e.key.toLowerCase();if(key==='z'){e.preventDefault();undo();return}if(multi&&['c','x','v'].includes(key)){e.preventDefault();if(key==='v')await paste();else await copy(key==='x')}});
 document.addEventListener('selectionchange',remember);
 root.addEventListener('keyup',remember);root.addEventListener('mouseup',remember);root.addEventListener('input',remember);
 root.addEventListener('click',e=>{const line=(e.target.closest('.outline-line')||current()?.querySelector(':scope > .outline-line'));if(!line)return;if(multi){e.preventDefault();const at=line.parentElement;if(selected.has(at))selected.delete(at);else selected.add(at);selectionChanged();return}const rect=line.getBoundingClientRect();if(e.clientX<rect.left){e.preventDefault();checkpoint();line.parentElement.open=!line.parentElement.open}else remember()});
 root.addEventListener('keydown',e=>{if(e.isComposing)return;const line=(e.target.closest('.outline-line')||current()?.querySelector(':scope > .outline-line'));if(!line)return;remember();if(e.key==='Tab'){e.preventDefault();indent(e.shiftKey)}else if(e.key==='Enter'){e.preventDefault();splitLine()}else if(e.key==='Backspace'&&saved?.collapsed){const before=saved.cloneRange();before.setStart(line,0);if(!before.toString()){e.preventDefault();const lines=[...root.querySelectorAll('.outline-line')].filter(n=>n.getClientRects().length),previousLine=lines[lines.indexOf(line)-1];if(!previousLine)return;checkpoint();const at=line.parentElement,previous=previousLine.parentElement,kids=at.querySelector(':scope > .outline-children');previousLine.append(...line.childNodes);if(kids?.children.length){let destination=previous.querySelector(':scope > .outline-children');if(!destination){destination=document.createElement('div');destination.className='outline-children';previous.append(destination)}destination.append(...kids.children)}at.remove();focus(previous)}}});
 root.addEventListener('paste',e=>{e.preventDefault();checkpoint();const text=e.clipboardData.getData('text/plain'),at=current();if(!at)return;const empty=!at.querySelector(':scope > .outline-line').textContent.trim();if(clipboard?.text===text){insertNodes(copiedNodes(),at,empty);return}if(empty&&text.includes('\n')){insertNodes(nodesFromText(text),at,true);return}const parts=text.replace(/\r/g,'').split('\n');remember();if(!saved)return;const r=saved.cloneRange();r.deleteContents();const t=document.createTextNode(parts.shift());r.insertNode(t);r.setStartAfter(t);r.collapse(true);getSelection().removeAllRanges();getSelection().addRange(r);if(parts.length)insertNodes(nodesFromText(parts.join('\n')),at);else remember()});

 function splitLine(){remember();const line=current()?.querySelector(':scope > .outline-line');if(!line||!saved)return;checkpoint();const r=saved.cloneRange();if(!line.contains(r.endContainer))return;r.deleteContents();const tail=r.cloneRange();tail.setEnd(line,line.childNodes.length);const next=block();next.firstChild.replaceChildren(tail.extractContents());if(!next.firstChild.textContent)next.firstChild.innerHTML='<br>';if(!line.textContent)line.innerHTML='<br>';line.parentElement.after(next);focus(next,false)}
 function removeSelected(){const nodes=selectedRoots();if(!nodes.length)return;checkpoint();nodes.forEach(n=>n.remove());selected.clear();selectionChanged();if(!root.children.length)root.append(block());saved=null}
 function selectedText(nodes){return nodes.map(n=>{const lines=[];function walk(b,depth){lines.push('  '.repeat(depth)+b.querySelector(':scope > .outline-line').textContent);b.querySelectorAll(':scope > .outline-children > .outline-node').forEach(c=>walk(c,depth+1))}walk(n,0);return lines.join('\n')}).join('\n')}
 async function copy(cut=false){const nodes=selectedRoots();if(!nodes.length)return;const text=selectedText(nodes);await navigator.clipboard.writeText(text);clipboard={text,html:nodes.map(n=>n.outerHTML).join('')};if(cut)removeSelected();else{selected.clear();selectionChanged()}}
 function copiedNodes(){const temp=document.createElement('div');temp.innerHTML=clipboard.html;for(const n of [...temp.querySelectorAll('.outline-node')].reverse()){const fresh=makeNode();fresh.open=!n.hasAttribute('data-collapsed');fresh.append(...n.childNodes);n.replaceWith(fresh)}return[...temp.children]}
 function nodesFromText(text){const temp=document.createElement('div'),stack=[];for(const raw of text.replace(/\r/g,'').split('\n')){const expanded=raw.replace(/^\t+/,tabs=>'  '.repeat(tabs.length)),spaces=expanded.match(/^ */)[0].length,depth=Math.min(Math.floor(spaces/2),stack.length),node=block();node.firstChild.textContent=expanded.slice(spaces)||' ';if(depth&&stack[depth-1]){let kids=stack[depth-1].querySelector(':scope > .outline-children');if(!kids){kids=document.createElement('div');kids.className='outline-children';stack[depth-1].append(kids)}kids.append(node)}else temp.append(node);stack[depth]=node;stack.length=depth+1}return[...temp.children]}
 function insertNodes(nodes,at=selectedRoots().at(-1)||current(),replaceEmpty=false){if(!nodes.length)return;if(replaceEmpty&&at)at.replaceWith(...nodes);else if(at)at.after(...nodes);else root.append(...nodes);decorate(root);let last=nodes.at(-1),child;while((child=last.querySelector(':scope > .outline-children > .outline-node:last-child')))last=child;focus(last)}
 async function paste(){const text=await navigator.clipboard.readText();if(!text)return;checkpoint();const at=selectedRoots().at(-1)||current(),empty=at&&!at.querySelector(':scope > .outline-line').textContent.trim();insertNodes(clipboard?.text===text?copiedNodes():nodesFromText(text),at,empty)}
 function restoreSelection(){if(!saved||!root.contains(saved.commonAncestorContainer))return false;root.focus({preventScroll:true});const selection=getSelection();selection.removeAllRanges();selection.addRange(saved.cloneRange());return true}
 return{load,add,indent,format,insertLink,remember,restoreSelection,toggleSelection,move,expand,placeholder,undo,copy,paste,removeSelected,selectionCount:()=>selectedRoots().length,html:()=>persisted(root.innerHTML)};
}
global.DriveMemoOutline={create};
})(window);
