(function(global){
"use strict";
// Each editable line owns its children; persisted markup contains no editor controls.
function create(root,{sanitize,decorate}){
 let saved=null;
 function remember(){const s=getSelection();if(s?.rangeCount&&root.contains(s.anchorNode)&&root.contains(s.focusNode))saved=s.getRangeAt(0).cloneRange()}
 function current(){const n=saved?.startContainer;return(n?.nodeType===1?n:n?.parentElement)?.closest('summary')?.parentElement||root.lastElementChild}
 function focus(block,end=true){const line=block.querySelector(':scope > summary');line.focus();const r=document.createRange();r.selectNodeContents(line);r.collapse(!end);getSelection().removeAllRanges();getSelection().addRange(r);remember()}
 function block(html=''){const d=document.createElement('details');d.open=true;const s=document.createElement('summary');s.contentEditable='true';s.setAttribute('role','textbox');s.setAttribute('aria-label','條列文字');s.innerHTML=html||'<br>';d.append(s);return d}
 function load(html){root.replaceChildren();const source=document.createElement('div');source.innerHTML=sanitize(html);function walk(container,target){for(const n of [...container.childNodes]){if(n.nodeType===3){if(n.textContent.trim())target.append(block(n.textContent.replace(/&/g,'&amp;').replace(/</g,'&lt;')));continue}if(n.nodeType!==1)continue;if(n.matches('details')){const summary=n.querySelector(':scope > summary'),d=block(summary?.innerHTML||'');d.open=n.hasAttribute('open');target.append(d);const kids=document.createElement('div');kids.className='outline-children';for(const child of [...n.children])if(child!==summary)walk(child,kids);if(kids.children.length)d.append(kids)}else if(n.matches('ul,ol')||n.classList.contains('outline-children')||n.classList.contains('outline-body'))walk(n,target);else if(n.matches('li')){const copy=n.cloneNode(true);copy.querySelectorAll('ul,ol').forEach(x=>x.remove());const d=block(copy.innerHTML);target.append(d);const kids=document.createElement('div');kids.className='outline-children';for(const list of n.querySelectorAll(':scope > ul,:scope > ol'))walk(list,kids);if(kids.children.length)d.append(kids)}else if(n.matches('p,div')&&n.querySelector('p,div,details,ul,ol'))walk(n,target);else if(n.textContent.trim()||n.querySelector('a')){for(const line of n.innerHTML.split(/<br\s*\/?>/i))target.append(block(line))}}}walk(source,root);if(!root.children.length)root.append(block());decorate(root);saved=null}
 function add(){remember();const at=current(),next=block();if(at)at.after(next);else root.append(next);focus(next)}
 function indent(out=false){remember();const at=current();if(!at)return;if(out){const parent=at.parentElement.closest('details');if(parent&&root.contains(parent))parent.after(at)}else{const prev=at.previousElementSibling;if(!prev?.matches('details'))return;let kids=prev.querySelector(':scope > .outline-children');if(!kids){kids=document.createElement('div');kids.className='outline-children';prev.append(kids)}kids.append(at);prev.open=true}focus(at)}
 function format(property,value){if(!saved||!root.contains(saved.commonAncestorContainer))return;const line=(saved.startContainer.nodeType===1?saved.startContainer:saved.startContainer.parentElement).closest('summary');if(!line)return;line.focus();const r=saved.cloneRange();if(r.collapsed)r.selectNodeContents(line);if(!line.contains(r.endContainer))return;const span=document.createElement('span');span.style[property]=value;const fragment=r.extractContents();for(const node of fragment.querySelectorAll('*')){node.style[property]='';if(property==='color')node.removeAttribute('color');if(property==='fontSize')node.removeAttribute('size')}span.append(fragment);r.insertNode(span);r.selectNodeContents(span);getSelection().removeAllRanges();getSelection().addRange(r);remember()}
 function insertLink(name,url){const at=current()||root.lastElementChild,line=at.querySelector(':scope > summary'),a=document.createElement('a');a.href=url;a.textContent=name;line.append(a);decorate(root);focus(at)}
 root.contentEditable='false';
 root.addEventListener('keyup',remember);root.addEventListener('mouseup',remember);root.addEventListener('input',remember);
 root.addEventListener('click',e=>{const line=e.target.closest('summary');if(!line)return;const rect=line.getBoundingClientRect();if(e.clientX>=rect.left){e.preventDefault();line.focus();remember()}});
 root.addEventListener('keydown',e=>{if(e.isComposing)return;const line=e.target.closest('summary');if(!line)return;remember();if(e.key==='Tab'){e.preventDefault();indent(e.shiftKey)}else if(e.key==='Enter'){e.preventDefault();const r=getSelection().getRangeAt(0);r.deleteContents();const tail=r.cloneRange();tail.setEnd(line,line.childNodes.length);const next=block();next.firstChild.replaceChildren(tail.extractContents());if(!next.firstChild.textContent&&!next.firstChild.children.length)next.firstChild.innerHTML='<br>';line.parentElement.after(next);focus(next,false)}else if(e.key==='Backspace'&&saved?.collapsed){const before=saved.cloneRange();before.setStart(line,0);if(!before.toString()){const at=line.parentElement,prev=at.previousElementSibling;if(prev?.matches('details')){e.preventDefault();const destination=prev.querySelector(':scope > summary');destination.append(...line.childNodes);const kids=at.querySelector(':scope > .outline-children');if(kids)prev.append(kids);at.remove();focus(prev)}else if(at.parentElement!==root){e.preventDefault();indent(true)}}}});
 root.addEventListener('paste',e=>{e.preventDefault();const text=e.clipboardData.getData('text/plain'),parts=text.replace(/\r/g,'').split('\n');remember();const at=current();if(!at||!saved)return;const r=saved.cloneRange();r.deleteContents();const t=document.createTextNode(parts.shift());r.insertNode(t);r.setStartAfter(t);r.collapse(true);getSelection().removeAllRanges();getSelection().addRange(r);let last=at;for(const part of parts){const next=block();next.firstChild.textContent=part;last.after(next);last=next}focus(last)});
 return{load,add,indent,format,insertLink,remember,html:()=>sanitize(root.innerHTML)};
}
global.DriveMemoOutline={create};
})(window);
