(function(global){
"use strict";
// Each editable line owns its children; persisted markup contains no editor controls.
function create(root,{sanitize,decorate}){
 let saved=null,multi=false;const selected=new Set(),history=[];let clipboard=null;
 function checkpoint(){const html=root.innerHTML;if(history.at(-1)!==html)history.push(html);if(history.length>100)history.shift()}
 function undo(){const html=history.pop();if(html===undefined)return;const wasMulti=multi;restore(html);if(wasMulti)toggleSelection();focus(root.firstElementChild,false)}
 function remember(){const s=getSelection();if(s?.rangeCount&&root.contains(s.anchorNode)&&root.contains(s.focusNode))saved=s.getRangeAt(0).cloneRange()}
 function current(){const n=saved?.startContainer;return(n?.nodeType===1?n:n?.parentElement)?.closest('summary')?.parentElement||root.lastElementChild}
 function focus(block,end=true){const line=block.querySelector(':scope > summary');line.focus();const r=document.createRange();r.selectNodeContents(line);r.collapse(!end);getSelection().removeAllRanges();getSelection().addRange(r);remember()}
 function block(html=''){const d=document.createElement('details');d.open=true;const s=document.createElement('summary');s.tabIndex=-1;s.setAttribute('role','textbox');s.setAttribute('aria-label','條列文字');s.innerHTML=html||'<br>';d.append(s);return d}
 function restore(html){selected.clear();multi=false;root.classList.remove('selecting');root.replaceChildren();const source=document.createElement('div');source.innerHTML=sanitize(html);function walk(container,target){for(const n of [...container.childNodes]){if(n.nodeType===3){if(n.textContent.trim())target.append(block(n.textContent.replace(/&/g,'&amp;').replace(/</g,'&lt;')));continue}if(n.nodeType!==1)continue;if(n.matches('details')){const summary=n.querySelector(':scope > summary'),d=block(summary?.innerHTML||'');d.open=n.hasAttribute('open');target.append(d);const kids=document.createElement('div');kids.className='outline-children';for(const child of [...n.children])if(child!==summary)walk(child,kids);if(kids.children.length)d.append(kids)}else if(n.matches('ul,ol')||n.classList.contains('outline-children')||n.classList.contains('outline-body'))walk(n,target);else if(n.matches('li')){const copy=n.cloneNode(true);copy.querySelectorAll('ul,ol').forEach(x=>x.remove());const d=block(copy.innerHTML);target.append(d);const kids=document.createElement('div');kids.className='outline-children';for(const list of n.querySelectorAll(':scope > ul,:scope > ol'))walk(list,kids);if(kids.children.length)d.append(kids)}else if(n.matches('p,div')&&n.querySelector('p,div,details,ul,ol'))walk(n,target);else if(n.textContent.trim()||n.querySelector('a')){for(const line of n.innerHTML.split(/<br\s*\/?>/i))target.append(block(line))}}}walk(source,root);if(!root.children.length)root.append(block());decorate(root);saved=null}
 function load(html){restore(html);history.length=0}
 function add(){checkpoint();remember();const at=current(),next=block();if(at)at.after(next);else root.append(next);focus(next)}
 function indent(out=false){remember();const targets=multi?selectedRoots():[current()].filter(Boolean);if(!targets.length)return;checkpoint();for(const at of out?[...targets].reverse():targets){if(out){const parent=at.parentElement.closest('details');if(parent&&root.contains(parent))parent.after(at)}else{let prev=at.previousElementSibling;while(prev&&selected.has(prev))prev=prev.previousElementSibling;if(!prev?.matches('details'))continue;let kids=prev.querySelector(':scope > .outline-children');if(!kids){kids=document.createElement('div');kids.className='outline-children';prev.append(kids)}kids.append(at);prev.open=true}}if(!multi)focus(targets[0])}
 function format(property,value){checkpoint();if(!saved||!root.contains(saved.commonAncestorContainer))return;const line=(saved.startContainer.nodeType===1?saved.startContainer:saved.startContainer.parentElement).closest('summary');if(!line)return;line.focus();const r=saved.cloneRange();if(r.collapsed)r.selectNodeContents(line);if(!line.contains(r.endContainer))return;const span=document.createElement('span');span.style[property]=value;const fragment=r.extractContents();for(const node of fragment.querySelectorAll('*')){node.style[property]='';if(property==='color')node.removeAttribute('color');if(property==='fontSize')node.removeAttribute('size')}span.append(fragment);r.insertNode(span);r.selectNodeContents(span);getSelection().removeAllRanges();getSelection().addRange(r);remember()}
 function insertLink(name,url){checkpoint();const at=current()||root.lastElementChild,line=at.querySelector(':scope > summary'),a=document.createElement('a');a.href=url;a.textContent=name;line.append(a);decorate(root);focus(at)}

 function toggleSelection(){multi=!multi;selected.clear();root.querySelectorAll('.outline-selected').forEach(n=>n.classList.remove('outline-selected'));root.classList.toggle('selecting',multi);return multi}
 function selectedRoots(){return [...root.querySelectorAll('details')].filter(n=>selected.has(n)&&![...selected].some(p=>p!==n&&p.contains(n)))}
 function move(delta){const list=selectedRoots();if(!list.length)return;checkpoint();const ordered=delta<0?list:[...list].reverse();for(const n of ordered){const neighbor=delta<0?n.previousElementSibling:n.nextElementSibling;if(neighbor&&!selected.has(neighbor)){if(delta<0)neighbor.before(n);else neighbor.after(n)}}list[0].scrollIntoView({block:'nearest'})}
 function expand(open){checkpoint();const targets=selectedRoots();if(!targets.length){const at=current();if(at)targets.push(at)}for(const at of targets){at.open=open;at.querySelectorAll('details').forEach(n=>n.open=open)}}
 function placeholder(name){checkpoint();const at=current(),next=block();const label=document.createElement('span');label.textContent='圖片描述：'+name;const status=document.createElement('span');status.contentEditable='false';status.className='upload-placeholder';status.textContent=' ⏳ 上傳中';next.firstChild.replaceChildren(label,status);if(at)at.after(next);else root.append(next);focus(next);return {complete(url){if(!root.contains(status))return;const line=status.closest('summary');if(!line)return;status.remove();const a=document.createElement('a');a.href=url;a.textContent=line.textContent||name;line.replaceChildren(a);decorate(root)},fail(){if(root.contains(next))status.textContent=' ⚠ 上傳失敗，請重新插入圖片'}}}
 root.addEventListener('keydown',e=>{if(e.isComposing||e.shiftKey||!['ArrowUp','ArrowDown'].includes(e.key))return;const line=(e.target.closest('summary')||current()?.querySelector(':scope > summary'));if(!line)return;const lines=[...root.querySelectorAll('summary')].filter(n=>n.getClientRects().length),next=lines[lines.indexOf(line)+(e.key==='ArrowUp'?-1:1)];if(next){e.preventDefault();focus(next.parentElement,e.key==='ArrowUp')}});
 root.contentEditable='true';
 root.addEventListener('beforeinput',e=>{if(e.inputType==='historyUndo'){e.preventDefault();undo();return}if(e.inputType==='insertParagraph'||e.inputType==='insertLineBreak'){e.preventDefault();splitLine();return}checkpoint()});
 root.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&!e.shiftKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}});
 document.addEventListener('selectionchange',remember);
 root.addEventListener('keyup',remember);root.addEventListener('mouseup',remember);root.addEventListener('input',remember);
 root.addEventListener('click',e=>{const line=(e.target.closest('summary')||current()?.querySelector(':scope > summary'));if(!line)return;if(multi){e.preventDefault();const at=line.parentElement;if(selected.has(at))selected.delete(at);else selected.add(at);at.classList.toggle('outline-selected',selected.has(at));return}const rect=line.getBoundingClientRect();if(e.clientX>=rect.left){e.preventDefault();remember()}});
 root.addEventListener('keydown',e=>{if(e.isComposing)return;const line=(e.target.closest('summary')||current()?.querySelector(':scope > summary'));if(!line)return;remember();if(e.key==='Tab'){e.preventDefault();indent(e.shiftKey)}else if(e.key==='Enter'){e.preventDefault();splitLine()}else if(e.key==='Backspace'&&saved?.collapsed){checkpoint();const before=saved.cloneRange();before.setStart(line,0);if(!before.toString()){const at=line.parentElement,prev=at.previousElementSibling;if(prev?.matches('details')){e.preventDefault();const destination=prev.querySelector(':scope > summary');destination.append(...line.childNodes);const kids=at.querySelector(':scope > .outline-children');if(kids)prev.append(kids);at.remove();focus(prev)}else if(at.parentElement!==root){e.preventDefault();indent(true)}}}});
 root.addEventListener('paste',e=>{e.preventDefault();checkpoint();const text=e.clipboardData.getData('text/plain'),parts=text.replace(/\r/g,'').split('\n');remember();const at=current();if(!at||!saved)return;const r=saved.cloneRange();r.deleteContents();const t=document.createTextNode(parts.shift());r.insertNode(t);r.setStartAfter(t);r.collapse(true);getSelection().removeAllRanges();getSelection().addRange(r);let last=at;for(const part of parts){const next=block();next.firstChild.textContent=part;last.after(next);last=next}focus(last)});

 function splitLine(){remember();const line=current()?.querySelector(':scope > summary');if(!line||!saved)return;checkpoint();const r=saved.cloneRange();if(!line.contains(r.endContainer))return;r.deleteContents();const tail=r.cloneRange();tail.setEnd(line,line.childNodes.length);const next=block();next.firstChild.replaceChildren(tail.extractContents());if(!next.firstChild.textContent)next.firstChild.innerHTML='<br>';if(!line.textContent)line.innerHTML='<br>';line.parentElement.after(next);focus(next,false)}
 function removeSelected(){const nodes=selectedRoots();if(!nodes.length)return;checkpoint();nodes.forEach(n=>n.remove());selected.clear();if(!root.children.length)root.append(block());saved=null}
 function selectedText(nodes){return nodes.map(n=>{const lines=[];function walk(b,depth){lines.push('  '.repeat(depth)+b.querySelector(':scope > summary').textContent);b.querySelectorAll(':scope > .outline-children > details').forEach(c=>walk(c,depth+1))}walk(n,0);return lines.join('\n')}).join('\n')}
 async function copy(cut=false){const nodes=selectedRoots();if(!nodes.length)return;const text=selectedText(nodes);await navigator.clipboard.writeText(text);clipboard={text,html:sanitize(nodes.map(n=>n.outerHTML).join(''))};if(cut)removeSelected()}
 async function paste(){const text=await navigator.clipboard.readText();if(!text)return;checkpoint();const temp=document.createElement('div');if(clipboard?.text===text){temp.innerHTML=clipboard.html;temp.querySelectorAll('summary').forEach(n=>{n.removeAttribute('contenteditable');n.tabIndex=-1})}else for(const value of text.replace(/\r/g,'').split('\n')){const n=block();n.firstChild.textContent=value||' ';temp.append(n)}const at=selectedRoots().at(-1)||current(),nodes=[...temp.children];if(at)at.after(...nodes);else root.append(...nodes);decorate(root);if(nodes.length)focus(nodes.at(-1))}
 return{load,add,indent,format,insertLink,remember,toggleSelection,move,expand,placeholder,undo,copy,paste,removeSelected,selectionCount:()=>selectedRoots().length,html:()=>sanitize(root.innerHTML)};
}
global.DriveMemoOutline={create};
})(window);
