(function(global){
"use strict";

const FORMAT="drive-memo-vault-v3",CATEGORY_KEYS=["A","B","C","D"],CATEGORY_TITLES=["工作","個人","財務","其他"];
const text=value=>String(value??"").trim();
const clone=value=>JSON.parse(JSON.stringify(value));
const uid=()=>global.crypto?.randomUUID?.()||`pw-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
function emptyData(){return{format:FORMAT,categoryNames:Object.fromEntries(CATEGORY_KEYS.map((key,index)=>[key,CATEGORY_TITLES[index]])),categories:Object.fromEntries(CATEGORY_KEYS.map(key=>[key,[]])),contactCategoryNames:Object.fromEntries(CATEGORY_KEYS.map((key,index)=>[key,CATEGORY_TITLES[index]])),contactCategories:Object.fromEntries(CATEGORY_KEYS.map(key=>[key,[]]))}}
function normalizeUrl(value){const url=text(value);if(!url)return"";try{const parsed=new URL(/^[a-z][a-z\d+.-]*:/i.test(url)?url:`https://${url}`);return["http:","https:"].includes(parsed.protocol)?parsed.href:""}catch{return""}}
function normalizeCredential(value={}){return{id:text(value.id)||uid(),name:text(value.name),account:text(value.account),password:String(value.password??""),note:String(value.note??"").trim()}}
function normalizeSite(value={}){return{id:text(value.id)||uid(),name:text(value.name)||"未命名網站",url:normalizeUrl(value.url),credentials:Array.isArray(value.credentials)?value.credentials.map(normalizeCredential):[]}}
function normalizeNamedValue(value={}){return{id:text(value.id)||uid(),name:text(value.name),value:text(value.value)}}
function normalizePerson(value={}){return{id:text(value.id)||uid(),name:text(value.name),departmentTitle:text(value.departmentTitle),phones:Array.isArray(value.phones)?value.phones.map(normalizeNamedValue).filter(item=>item.name||item.value):[],documents:Array.isArray(value.documents)?value.documents.map(normalizeNamedValue).filter(item=>item.name||item.value):[],address:text(value.address),note:String(value.note??"").trim()}}
function normalizeCompany(value={}){return{id:text(value.id)||uid(),name:text(value.name)||"未命名公司",people:Array.isArray(value.people)?value.people.map(normalizePerson):[]}}
function parse(source){let raw;try{raw=typeof source==="string"?JSON.parse(source):source}catch{return emptyData()}const categoryNames={},categories={},contactCategoryNames={},contactCategories={};CATEGORY_KEYS.forEach((key,index)=>{const legacy=Array.isArray(raw?.columns)?raw.columns[index]:null;categoryNames[key]=text(raw?.categoryNames?.[key])||text(legacy?.title)||CATEGORY_TITLES[index];const sites=Array.isArray(raw?.categories?.[key])?raw.categories[key]:legacy?.sites;categories[key]=Array.isArray(sites)?sites.map(normalizeSite):[];contactCategoryNames[key]=text(raw?.contactCategoryNames?.[key])||CATEGORY_TITLES[index];const companies=raw?.contactCategories?.[key];contactCategories[key]=Array.isArray(companies)?companies.map(normalizeCompany):[]});return{format:FORMAT,categoryNames,categories,contactCategoryNames,contactCategories}}
function serialize(data){return JSON.stringify(parse(data),null,2)}
function syncDisposition(baseContent,localContent,cloudContent){if(cloudContent===localContent)return"same";if(baseContent&&cloudContent===baseContent)return"retry";return"conflict"}
function findSite(data,siteId){for(const category of CATEGORY_KEYS){const site=data.categories[category].find(value=>value.id===siteId);if(site)return{category,site}}return null}
function renameCategory(data,category,name){const next=parse(clone(data));if(CATEGORY_KEYS.includes(category)&&text(name))next.categoryNames[category]=text(name);return next}
function addSite(data,category,input){const next=parse(clone(data)),key=CATEGORY_KEYS.includes(category)?category:"A",site=normalizeSite(input);if(!text(input?.name))throw new Error("請輸入網站名稱");next.categories[key].push(site);return{data:next,siteId:site.id}}
function updateSite(data,siteId,input){const next=parse(clone(data)),found=findSite(next,siteId);if(!found)throw new Error("找不到網站");if(!text(input?.name))throw new Error("請輸入網站名稱");found.site.name=text(input.name);found.site.url=normalizeUrl(input.url);const destination=CATEGORY_KEYS.includes(input.category)?input.category:found.category;if(destination!==found.category){next.categories[found.category]=next.categories[found.category].filter(value=>value.id!==siteId);next.categories[destination].push(found.site)}return next}
function removeSite(data,siteId){const next=parse(clone(data));for(const category of CATEGORY_KEYS)next.categories[category]=next.categories[category].filter(value=>value.id!==siteId);return next}
function upsertCredential(data,siteId,input,credentialId=""){const next=parse(clone(data)),found=findSite(next,siteId);if(!found)throw new Error("找不到網站");const value=normalizeCredential({...input,id:credentialId||undefined});if(!value.name)throw new Error("請輸入名稱");if(credentialId){const index=found.site.credentials.findIndex(item=>item.id===credentialId);if(index<0)throw new Error("找不到帳密");found.site.credentials[index]=value}else found.site.credentials.push(value);return{data:next,credentialId:value.id}}
function removeCredential(data,siteId,credentialId){const next=parse(clone(data)),found=findSite(next,siteId);if(found)found.site.credentials=found.site.credentials.filter(value=>value.id!==credentialId);return next}
function findCompany(data,companyId){for(const category of CATEGORY_KEYS){const company=data.contactCategories[category].find(value=>value.id===companyId);if(company)return{category,company}}return null}
function renameContactCategory(data,category,name){const next=parse(clone(data));if(CATEGORY_KEYS.includes(category)&&text(name))next.contactCategoryNames[category]=text(name);return next}
function addCompany(data,category,input){const next=parse(clone(data)),key=CATEGORY_KEYS.includes(category)?category:"A",company=normalizeCompany(input);if(!text(input?.name))throw new Error("請輸入公司名稱");next.contactCategories[key].push(company);return{data:next,companyId:company.id}}
function updateCompany(data,companyId,input){const next=parse(clone(data)),found=findCompany(next,companyId);if(!found)throw new Error("找不到公司");if(!text(input?.name))throw new Error("請輸入公司名稱");found.company.name=text(input.name);const destination=CATEGORY_KEYS.includes(input.category)?input.category:found.category;if(destination!==found.category){next.contactCategories[found.category]=next.contactCategories[found.category].filter(value=>value.id!==companyId);next.contactCategories[destination].push(found.company)}return next}
function removeCompany(data,companyId){const next=parse(clone(data));for(const category of CATEGORY_KEYS)next.contactCategories[category]=next.contactCategories[category].filter(value=>value.id!==companyId);return next}
function upsertPerson(data,companyId,input,personId=""){const next=parse(clone(data)),found=findCompany(next,companyId);if(!found)throw new Error("找不到公司");const value=normalizePerson({...input,id:personId||undefined});if(!value.name)throw new Error("請輸入姓名");if(personId){const index=found.company.people.findIndex(item=>item.id===personId);if(index<0)throw new Error("找不到聯絡人");found.company.people[index]=value}else found.company.people.push(value);return{data:next,personId:value.id}}
function removePerson(data,companyId,personId){const next=parse(clone(data)),found=findCompany(next,companyId);if(found)found.company.people=found.company.people.filter(value=>value.id!==personId);return next}

function create(options={}){
 const byId=id=>document.getElementById(id),escape=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
 const cloud=options.cloud,fileIdInput=byId("passwordFileId"),board=byId("passwordBoard"),panel=byId("passwordDetailPanel"),host=byId("passwordDetailHost"),detailDialog=byId("passwordDetailDialog"),dialogBody=byId("passwordDetailDialogBody"),status=byId("passwordStatus"),siteDialog=byId("passwordSiteDialog"),siteForm=byId("passwordSiteForm"),credentialDialog=byId("credentialDialog"),credentialForm=byId("credentialForm"),conflictDialog=byId("passwordConflictDialog"),contactBoard=byId("contactBoard"),contactPanel=byId("contactDetailPanel"),contactHost=byId("contactDetailHost"),contactDetailDialog=byId("contactDetailDialog"),contactDialogBody=byId("contactDetailDialogBody"),contactStatus=byId("contactStatus"),companyDialog=byId("companyDialog"),companyForm=byId("companyForm"),personDialog=byId("personDialog"),personForm=byId("personForm");
 let data=emptyData(),selectedSiteId="",selectedCompanyId="",baseVersion=null,baseContent="",dirty=false,active=false,loading=false,saving=false,saveTimer=null,pendingCloud=null,storageKey="";const revealed=new Set();
 const key=()=>`driveMemoPasswords:${(text(fileIdInput.value)||"local").replace(/[^a-zA-Z0-9_-]/g,"_")}`;
 function setStatus(message,kind=""){for(const node of [status,contactStatus]){node.textContent=message;node.className=`password-status ${kind}`.trim()}}
 function persist(){try{localStorage.setItem(storageKey||key(),JSON.stringify({content:serialize(data),dirty,baseVersion,baseContent}))}catch{setStatus("瀏覽器無法儲存本機副本","err")}}
 function restore(){try{const saved=JSON.parse(localStorage.getItem(storageKey||key())||"null");if(saved?.content){data=parse(saved.content);dirty=Boolean(saved.dirty);baseVersion=saved.baseVersion==null?null:String(saved.baseVersion);baseContent=typeof saved.baseContent==="string"?serialize(parse(saved.baseContent)):dirty?"":serialize(data);return true}}catch{}data=emptyData();dirty=false;baseVersion=null;baseContent="";return false}
 function selected(){return selectedSiteId?findSite(data,selectedSiteId):null}
 function selectedCompany(){return selectedCompanyId?findCompany(data,selectedCompanyId):null}
 function renderBoard(){board.innerHTML=CATEGORY_KEYS.map(category=>{const title=data.categoryNames[category],sites=data.categories[category];return`<section class="password-column" data-password-category-column="${category}"><label class="password-category-label"><span>${category}</span><input class="password-category-name" data-password-category-name="${category}" value="${escape(title)}" maxlength="40" aria-label="${category} 分類名稱"></label><div class="password-site-list">${sites.map(site=>`<button type="button" class="password-site-card${site.id===selectedSiteId?" active":""}" data-password-site="${escape(site.id)}"><strong>${escape(site.name)}</strong><span>${site.credentials.length} 組帳密</span></button>`).join("")}</div><button type="button" class="password-add-site" data-password-add-site="${category}" aria-label="在${escape(title)}新增網站">＋</button></section>`}).join("")}
 function renderDetail(){const found=selected();if(!found){panel.innerHTML='<div class="password-empty"><strong>選擇一個網站</strong><span>帳號、密碼與備註會顯示在這裡。</span></div>';return}const {site}=found,url=site.url?`<a class="password-site-link" href="${escape(site.url)}" target="_blank" rel="noopener noreferrer">開啟網站 ↗</a>`:"";panel.innerHTML=`<header class="password-detail-head"><div><h2>${escape(site.name)}</h2>${url}</div><div class="row"><button type="button" class="btn" data-password-edit-site>編輯網站</button><button type="button" class="btn primary" data-password-add-credential>新增帳密</button></div></header><div class="password-records">${site.credentials.length?site.credentials.map(item=>`<article class="password-record" data-credential-id="${escape(item.id)}"><div class="password-record-row"><span>名稱</span><strong>${escape(item.name)}</strong><button type="button" class="icon-btn" data-password-edit-credential="${escape(item.id)}" aria-label="編輯${escape(item.name)}">✎</button></div><div class="password-record-row"><span>帳號</span><button type="button" class="password-copy" data-password-copy="${escape(item.id)}" data-copy-field="account" ${item.account?"":"disabled"}>${escape(item.account)||"—"}</button></div><div class="password-record-row"><span>密碼</span><button type="button" class="password-copy password-secret" data-password-copy="${escape(item.id)}" data-copy-field="password" ${item.password?"":"disabled"}>${revealed.has(item.id)?escape(item.password):(item.password?"••••••••":"—")}</button><button type="button" class="password-reveal" data-password-reveal="${escape(item.id)}">${revealed.has(item.id)?"隱藏":"顯示"}</button></div><div class="password-record-row"><span>備註</span><p>${escape(item.note)||"—"}</p></div></article>`).join(""):'<div class="password-empty"><span>這個網站還沒有帳密。</span></div>'}</div>`}
 function renderContactBoard(){contactBoard.innerHTML=CATEGORY_KEYS.map(category=>{const title=data.contactCategoryNames[category],companies=data.contactCategories[category];return`<section class="password-column" data-contact-category-column="${category}"><label class="password-category-label"><span>${category}</span><input class="password-category-name" data-contact-category-name="${category}" value="${escape(title)}" maxlength="40" aria-label="${category} 分類名稱"></label><div class="password-site-list">${companies.map(company=>`<button type="button" class="password-site-card${company.id===selectedCompanyId?" active":""}" data-contact-company="${escape(company.id)}"><strong>${escape(company.name)}</strong><span>${company.people.length} 位聯絡人</span></button>`).join("")}</div><button type="button" class="password-add-site" data-contact-add-company="${category}" aria-label="在${escape(title)}新增公司">＋</button></section>`}).join("")}
 function namedValues(items,emptyLabel,phone=false){return items.length?items.map(item=>`<div class="contact-value"><span>${escape(item.name)||emptyLabel}</span>${phone&&item.value?`<a href="tel:${escape(item.value.replace(/[^+\d,;#*]/g,""))}">${escape(item.value)}</a>`:`<strong>${escape(item.value)||"—"}</strong>`}</div>`).join(""):'<span class="contact-none">—</span>'}
 function renderContactDetail(){const found=selectedCompany();if(!found){contactPanel.innerHTML='<div class="password-empty"><strong>選擇一家公司</strong><span>右側會顯示該公司的聯絡人。</span></div>';return}const {company}=found;contactPanel.innerHTML=`<header class="password-detail-head"><div><h2>${escape(company.name)}</h2></div><div class="row"><button type="button" class="btn" data-contact-edit-company>編輯公司</button><button type="button" class="btn primary" data-contact-add-person>新增聯絡人</button></div></header><div class="password-records">${company.people.length?company.people.map(person=>`<article class="password-record contact-card" data-person-id="${escape(person.id)}"><div class="password-record-row"><span>姓名</span><strong>${escape(person.name)}</strong><button type="button" class="icon-btn" data-contact-edit-person="${escape(person.id)}" aria-label="編輯${escape(person.name)}">✎</button></div><div class="password-record-row"><span>部門／職稱</span><p>${escape(person.departmentTitle)||"—"}</p></div><div class="password-record-row contact-multi-row"><span>電話</span><div>${namedValues(person.phones,"電話",true)}</div></div><div class="password-record-row contact-multi-row"><span>證件號</span><div>${namedValues(person.documents,"證件")}</div></div><div class="password-record-row"><span>地址</span><p>${escape(person.address)||"—"}</p></div><div class="password-record-row"><span>備註</span><p>${escape(person.note)||"—"}</p></div></article>`).join(""):'<div class="password-empty"><span>這家公司還沒有聯絡人。</span></div>'}</div>`}
 function render(){renderBoard();renderDetail();renderContactBoard();renderContactDetail()}
 function showSelected(){render();if(innerWidth<=820&&selected()){dialogBody.append(panel);if(!detailDialog.open)detailDialog.showModal()}else{if(detailDialog.open)detailDialog.close();host.append(panel)}}
 function showSelectedCompany(){render();if(innerWidth<=820&&selectedCompany()){contactDialogBody.append(contactPanel);if(!contactDetailDialog.open)contactDetailDialog.showModal()}else{if(contactDetailDialog.open)contactDetailDialog.close();contactHost.append(contactPanel)}}
 function mutate(next){data=parse(next);dirty=true;persist();render();clearTimeout(saveTimer);if(!pendingCloud)saveTimer=setTimeout(saveNow,500)}
 function showConflict(snapshot){pendingCloud=snapshot;byId("passwordConflictMessage").textContent="這份密碼與通訊錄檔案在雲端也有更新。請選擇保留雲端版本或本機版本。";if(!conflictDialog.open)conflictDialog.showModal();setStatus("發現同步衝突","err")}
 async function loadCloud(){if(loading)return;if(!text(fileIdInput.value)){setStatus("請先在後台設定密碼與通訊錄文件 ID","");return}if(navigator.onLine===false){setStatus("離線：已載入本機密碼與通訊錄","");return}loading=true;setStatus("正在讀取密碼與通訊錄…","sync");try{const snapshot=await cloud.readCloudFile(fileIdInput.value),cloudData=parse(snapshot.content),cloudText=serialize(cloudData),localText=serialize(data),disposition=syncDisposition(baseContent,localText,cloudText);if(dirty&&disposition==="conflict"){showConflict(snapshot);return}if(dirty&&disposition==="retry"){baseVersion=String(snapshot.meta.version??"");persist();await saveNow();return}data=cloudData;baseVersion=String(snapshot.meta.version??"");baseContent=cloudText;dirty=false;persist();render();setStatus("密碼與通訊錄已同步","ok")}catch(error){setStatus(error.message==="AUTH_EXPIRED"?"正在恢復登入…":`檔案讀取失敗：${error.message}`,"err")}finally{loading=false}}
 async function saveNow(force=false){clearTimeout(saveTimer);saveTimer=null;if(!dirty||saving||pendingCloud&&!force)return;if(!text(fileIdInput.value)){persist();setStatus("本機已儲存；設定共用文件 ID 後可同步","");return}if(navigator.onLine===false){persist();setStatus("離線：修改已保存在本機","");return}saving=true;const content=serialize(data);setStatus("正在同步密碼與通訊錄…","sync");try{let result=await cloud.writeCloudFile(fileIdInput.value,content,baseVersion,{force});if(result.conflict){const cloudText=serialize(parse(result.snapshot.content)),disposition=syncDisposition(baseContent,content,cloudText);if(disposition==="same"){baseVersion=String(result.snapshot.meta.version??"");baseContent=cloudText;dirty=serialize(data)!==content;persist();setStatus(dirty?"繼續同步最新修改…":"密碼與通訊錄已同步",dirty?"sync":"ok");return}if(disposition==="retry"){baseVersion=String(result.snapshot.meta.version??"");result=await cloud.writeCloudFile(fileIdInput.value,content,baseVersion);if(result.conflict){showConflict(result.snapshot);return}}else{showConflict(result.snapshot);return}}baseVersion=String(result.meta.version??"");baseContent=content;dirty=serialize(data)!==content;persist();setStatus(dirty?"已同步上一批修改，繼續儲存…":"密碼與通訊錄已同步",dirty?"sync":"ok")}catch(error){persist();setStatus(error.message==="AUTH_EXPIRED"?"修改已保留，正在恢復登入…":`修改已保留：${error.message}`,"err")}finally{saving=false;if(dirty&&!pendingCloud)saveTimer=setTimeout(saveNow,500)}}
 function updateCategorySelect(){byId("passwordSiteColumn").innerHTML=CATEGORY_KEYS.map(category=>`<option value="${category}">${escape(data.categoryNames[category])}</option>`).join("")}
 function editSite(siteId="",category="A"){const found=siteId?findSite(data,siteId):null;updateCategorySelect();byId("passwordSiteId").value=siteId;byId("passwordSiteName").value=found?.site.name||"";byId("passwordSiteUrl").value=found?.site.url||"";byId("passwordSiteColumn").value=found?.category||category;byId("deletePasswordSiteBtn").classList.toggle("hidden",!found);siteDialog.showModal();setTimeout(()=>byId("passwordSiteName").focus(),0)}
 function editCredential(credentialId=""){const site=selected()?.site,item=site?.credentials.find(value=>value.id===credentialId);byId("credentialId").value=credentialId;byId("credentialName").value=item?.name||"";byId("credentialAccount").value=item?.account||"";byId("credentialPassword").value=item?.password||"";byId("credentialNote").value=item?.note||"";byId("deleteCredentialBtn").classList.toggle("hidden",!item);credentialDialog.showModal();setTimeout(()=>byId("credentialName").focus(),0)}
 async function copyCredential(button){const item=selected()?.site.credentials.find(value=>value.id===button.dataset.passwordCopy),field=button.dataset.copyField,value=item?.[field]||"";if(!value)return;try{await navigator.clipboard.writeText(value);button.classList.add("copied");button.setAttribute("aria-label",field==="password"?"密碼已複製":"帳號已複製");setStatus(field==="password"?"密碼已複製":"帳號已複製","ok");setTimeout(()=>button.isConnected&&button.classList.remove("copied"),900)}catch{setStatus("無法存取剪貼簿，請允許剪貼簿權限","err")}}
 function updateContactCategorySelect(){byId("companyCategory").innerHTML=CATEGORY_KEYS.map(category=>`<option value="${category}">${escape(data.contactCategoryNames[category])}</option>`).join("")}
 function editCompany(companyId="",category="A"){const found=companyId?findCompany(data,companyId):null;updateContactCategorySelect();byId("companyId").value=companyId;byId("companyName").value=found?.company.name||"";byId("companyCategory").value=found?.category||category;byId("deleteCompanyBtn").classList.toggle("hidden",!found);companyDialog.showModal();setTimeout(()=>byId("companyName").focus(),0)}
 function repeaterRow(kind,item={}){const label=kind==="phone"?"例如：手機":"例如：台胞證",value=kind==="phone"?"電話號碼":"證件號碼";return`<div class="contact-field-row" data-contact-field-row><input data-contact-field-name maxlength="80" placeholder="${label}" value="${escape(item.name||"")}" aria-label="名稱"><span aria-hidden="true">：</span><input data-contact-field-value maxlength="500" placeholder="${value}" value="${escape(item.value||"")}" aria-label="值"><button type="button" class="icon-btn" data-contact-remove-row aria-label="移除此列">×</button></div>`}
 function setRepeater(kind,items=[]){const list=byId(kind==="phone"?"personPhones":"personDocuments");list.innerHTML=(items.length?items:[{}]).map(item=>repeaterRow(kind,item)).join("")}
 function readRepeater(id){return[...byId(id).querySelectorAll("[data-contact-field-row]")].map(row=>({name:row.querySelector("[data-contact-field-name]").value,value:row.querySelector("[data-contact-field-value]").value})).filter(item=>text(item.name)||text(item.value))}
 function editPerson(personId=""){const company=selectedCompany()?.company,item=company?.people.find(value=>value.id===personId);byId("personId").value=personId;byId("personName").value=item?.name||"";byId("personDepartmentTitle").value=item?.departmentTitle||"";byId("personAddress").value=item?.address||"";byId("personNote").value=item?.note||"";setRepeater("phone",item?.phones);setRepeater("document",item?.documents);byId("deletePersonBtn").classList.toggle("hidden",!item);personDialog.showModal();setTimeout(()=>byId("personName").focus(),0)}
 function bind(){
  board.addEventListener("click",event=>{const add=event.target.closest("[data-password-add-site]"),site=event.target.closest("[data-password-site]");if(add)editSite("",add.dataset.passwordAddSite);if(site){selectedSiteId=site.dataset.passwordSite;showSelected()}});
  board.addEventListener("change",event=>{const input=event.target.closest("[data-password-category-name]");if(!input)return;const name=text(input.value);if(!name){input.value=data.categoryNames[input.dataset.passwordCategoryName];return}mutate(renameCategory(data,input.dataset.passwordCategoryName,name))});
  panel.addEventListener("click",async event=>{const copy=event.target.closest("[data-password-copy]"),reveal=event.target.closest("[data-password-reveal]"),edit=event.target.closest("[data-password-edit-credential]");if(copy){await copyCredential(copy);return}if(reveal){revealed.has(reveal.dataset.passwordReveal)?revealed.delete(reveal.dataset.passwordReveal):revealed.add(reveal.dataset.passwordReveal);renderDetail()}if(edit)editCredential(edit.dataset.passwordEditCredential);if(event.target.closest("[data-password-add-credential]"))editCredential();if(event.target.closest("[data-password-edit-site]"))editSite(selectedSiteId)});
  byId("closePasswordDetailBtn").addEventListener("click",()=>detailDialog.close());detailDialog.addEventListener("close",()=>host.append(panel));
  siteForm.addEventListener("submit",event=>{event.preventDefault();try{const id=byId("passwordSiteId").value,input={name:byId("passwordSiteName").value,url:byId("passwordSiteUrl").value,category:byId("passwordSiteColumn").value};if(id)mutate(updateSite(data,id,input));else{const added=addSite(data,input.category,input);selectedSiteId=added.siteId;mutate(added.data)}siteDialog.close();showSelected()}catch(error){setStatus(error.message,"err")}});
  byId("cancelPasswordSiteBtn").addEventListener("click",()=>siteDialog.close());byId("deletePasswordSiteBtn").addEventListener("click",()=>{if(!selectedSiteId||!confirm("刪除這個網站及其所有帳密？"))return;mutate(removeSite(data,selectedSiteId));selectedSiteId="";siteDialog.close();showSelected()});
  credentialForm.addEventListener("submit",event=>{event.preventDefault();try{const id=byId("credentialId").value,result=upsertCredential(data,selectedSiteId,{name:byId("credentialName").value,account:byId("credentialAccount").value,password:byId("credentialPassword").value,note:byId("credentialNote").value},id);mutate(result.data);credentialDialog.close()}catch(error){setStatus(error.message,"err")}});
  byId("cancelCredentialBtn").addEventListener("click",()=>credentialDialog.close());byId("deleteCredentialBtn").addEventListener("click",()=>{const id=byId("credentialId").value;if(!id||!confirm("刪除這組帳密？"))return;mutate(removeCredential(data,selectedSiteId,id));revealed.delete(id);credentialDialog.close()});
  contactBoard.addEventListener("click",event=>{const add=event.target.closest("[data-contact-add-company]"),company=event.target.closest("[data-contact-company]");if(add)editCompany("",add.dataset.contactAddCompany);if(company){selectedCompanyId=company.dataset.contactCompany;showSelectedCompany()}});
  contactBoard.addEventListener("change",event=>{const input=event.target.closest("[data-contact-category-name]");if(!input)return;const name=text(input.value);if(!name){input.value=data.contactCategoryNames[input.dataset.contactCategoryName];return}mutate(renameContactCategory(data,input.dataset.contactCategoryName,name))});
  contactPanel.addEventListener("click",event=>{const edit=event.target.closest("[data-contact-edit-person]");if(edit)editPerson(edit.dataset.contactEditPerson);if(event.target.closest("[data-contact-add-person]"))editPerson();if(event.target.closest("[data-contact-edit-company]"))editCompany(selectedCompanyId)});
  byId("closeContactDetailBtn").addEventListener("click",()=>contactDetailDialog.close());contactDetailDialog.addEventListener("close",()=>contactHost.append(contactPanel));
  companyForm.addEventListener("submit",event=>{event.preventDefault();try{const id=byId("companyId").value,input={name:byId("companyName").value,category:byId("companyCategory").value};if(id)mutate(updateCompany(data,id,input));else{const added=addCompany(data,input.category,input);selectedCompanyId=added.companyId;mutate(added.data)}companyDialog.close();showSelectedCompany()}catch(error){setStatus(error.message,"err")}});
  byId("cancelCompanyBtn").addEventListener("click",()=>companyDialog.close());byId("deleteCompanyBtn").addEventListener("click",()=>{if(!selectedCompanyId||!confirm("刪除這家公司及其所有聯絡人？"))return;mutate(removeCompany(data,selectedCompanyId));selectedCompanyId="";companyDialog.close();showSelectedCompany()});
  byId("personFields").addEventListener("click",event=>{const add=event.target.closest("[data-contact-add-row]"),remove=event.target.closest("[data-contact-remove-row]");if(add){const kind=add.dataset.contactAddRow,list=byId(kind==="phone"?"personPhones":"personDocuments");list.insertAdjacentHTML("beforeend",repeaterRow(kind));list.lastElementChild.querySelector("input").focus()}if(remove){const list=remove.closest(".contact-field-list");remove.closest("[data-contact-field-row]").remove();if(!list.children.length)list.insertAdjacentHTML("beforeend",repeaterRow(list.id==="personPhones"?"phone":"document"))}});
  personForm.addEventListener("submit",event=>{event.preventDefault();try{const id=byId("personId").value,result=upsertPerson(data,selectedCompanyId,{name:byId("personName").value,departmentTitle:byId("personDepartmentTitle").value,phones:readRepeater("personPhones"),documents:readRepeater("personDocuments"),address:byId("personAddress").value,note:byId("personNote").value},id);mutate(result.data);personDialog.close()}catch(error){setStatus(error.message,"err")}});
  byId("cancelPersonBtn").addEventListener("click",()=>personDialog.close());byId("deletePersonBtn").addEventListener("click",()=>{const id=byId("personId").value;if(!id||!confirm("刪除這位聯絡人？"))return;mutate(removePerson(data,selectedCompanyId,id));personDialog.close()});
  byId("reloadPasswordsBtn").addEventListener("click",loadCloud);byId("reloadContactsBtn").addEventListener("click",loadCloud);byId("openPasswordsBtn").addEventListener("click",()=>{fileIdChanged();active=true;location.hash="#passwords";loadCloud()});fileIdInput.addEventListener("change",fileIdChanged);
  byId("passwordUseCloudBtn").addEventListener("click",()=>{if(!pendingCloud)return;try{localStorage.setItem(`${key()}:backup:${Date.now()}`,serialize(data))}catch{}data=parse(pendingCloud.content);baseVersion=String(pendingCloud.meta.version??"");baseContent=serialize(data);dirty=false;pendingCloud=null;persist();render();conflictDialog.close();setStatus("已採用雲端密碼與通訊錄","ok")});
  byId("passwordKeepLocalBtn").addEventListener("click",async()=>{if(pendingCloud){baseVersion=String(pendingCloud.meta.version??"");baseContent=serialize(parse(pendingCloud.content))}pendingCloud=null;conflictDialog.close();await saveNow(true)});byId("passwordConflictLaterBtn").addEventListener("click",()=>conflictDialog.close());
  addEventListener("resize",()=>{if(innerWidth>820){if(detailDialog.open)detailDialog.close();if(contactDetailDialog.open)contactDetailDialog.close();host.append(panel);contactHost.append(contactPanel)}});addEventListener("online",()=>{if(active)(dirty?saveNow():loadCloud())});addEventListener("pagehide",persist)
 }
 function fileIdChanged(){clearTimeout(saveTimer);persist();storageKey=key();selectedSiteId="";selectedCompanyId="";baseVersion=null;baseContent="";dirty=false;pendingCloud=null;restore();render();options.onFileIdChange?.(text(fileIdInput.value))}
 function initialize(){storageKey=key();restore();render();bind()}
 function activate(){active=true;render();if(text(fileIdInput.value))loadCloud();else setStatus("請先在後台設定密碼與通訊錄文件 ID","")}
 function connected(){if(active&&text(fileIdInput.value))(dirty?saveNow():loadCloud())}
 return Object.freeze({initialize,activate,connected,fileIdChanged,loadCloud,saveNow,getData:()=>parse(clone(data))});
}

global.DriveMemoPasswords=Object.freeze({FORMAT,CATEGORY_KEYS,CATEGORY_TITLES,emptyData,normalizeUrl,parse,serialize,syncDisposition,findSite,renameCategory,addSite,updateSite,removeSite,upsertCredential,removeCredential,findCompany,renameContactCategory,addCompany,updateCompany,removeCompany,upsertPerson,removePerson,create});
})(window);
