(function(global){
"use strict";

const Content=global.DriveMemoContent;
const byId=id=>document.getElementById(id);
const els={
 journalNav:byId("journalNav"),projectsNav:byId("projectsNav"),debugNav:byId("debugNav"),journalPage:byId("journalPage"),projectsPage:byId("projectsPage"),debugPage:byId("debugPage"),projectsList:byId("projectsList"),
 loginBtn:byId("loginBtn"),logoutBtn:byId("logoutBtn"),openBtn:byId("openBtn"),syncBtn:byId("syncBtn"),
 fileId:byId("fileId"),editor:byId("editor"),preview:byId("preview"),statusText:byId("statusText"),stateDot:byId("stateDot"),
 fileMeta:byId("fileMeta"),dirtyState:byId("dirtyState"),identity:byId("identity"),addBulletBtn:byId("addBulletBtn"),agenda:byId("agenda"),
 rolloverPanel:byId("rolloverPanel"),rolloverSummary:byId("rolloverSummary"),rolloverList:byId("rolloverList"),
 rolloverSelectedBtn:byId("rolloverSelectedBtn"),rolloverAllBtn:byId("rolloverAllBtn"),bulletDialog:byId("bulletDialog"),bulletForm:byId("bulletForm"),
 bulletDialogTitle:byId("bulletDialogTitle"),bulletId:byId("bulletId"),bulletProjectId:byId("bulletProjectId"),bulletMode:byId("bulletMode"),projectNameField:byId("projectNameField"),actionField:byId("actionField"),actionDateField:byId("actionDateField"),actionPriorityField:byId("actionPriorityField"),bulletTitle:byId("bulletTitle"),bulletAction:byId("bulletAction"),bulletDate:byId("bulletDate"),bulletDateButton:byId("bulletDateButton"),datePicker:byId("datePicker"),calendarTitle:byId("calendarTitle"),calendarGrid:byId("calendarGrid"),
 bulletPriority:byId("bulletPriority"),priorityPicker:byId("priorityPicker"),bulletDetails:byId("bulletDetails"),bulletDetailsLabel:byId("bulletDetailsLabel"),goToProjectBtn:byId("goToProjectBtn"),projectDetailsTools:byId("projectDetailsTools"),detailsWorkspace:byId("detailsWorkspace"),projectRichEditor:byId("projectRichEditor"),projectTextSize:byId("projectTextSize"),projectTextColor:byId("projectTextColor"),projectImageBtn:byId("projectImageBtn"),projectImageInput:byId("projectImageInput"),bulletHistoryField:byId("bulletHistoryField"),bulletHistory:byId("bulletHistory"),deleteBulletBtn:byId("deleteBulletBtn"),convertProjectBtn:byId("convertProjectBtn"),cancelBulletBtn:byId("cancelBulletBtn"),
 toast:byId("toast"),toastText:byId("toastText"),undoDeleteBtn:byId("undoDeleteBtn"),conflictDialog:byId("conflictDialog"),diffView:byId("diffView"),
 localConflict:byId("localConflict"),cloudConflict:byId("cloudConflict"),laterBtn:byId("laterBtn"),cloudBtn:byId("cloudBtn"),localBtn:byId("localBtn"),imageHover:byId("imageHover"),imageDialog:byId("imageDialog"),imageDialogTitle:byId("imageDialogTitle"),imageDialogImg:byId("imageDialogImg"),closeImageBtn:byId("closeImageBtn"),convertDialog:byId("convertDialog"),convertForm:byId("convertForm"),convertProjectName:byId("convertProjectName"),cancelConvertBtn:byId("cancelConvertBtn")
};

const priorityNames={urgent:"立即處理",today:"今天完成",soon:"這幾天",someday:"慢慢做"},RICH_DETAILS_MARKER="<!-- DRIVE_MEMO_RICH_DETAILS_V1 -->";
let selectedDate=Content.localDateKey(),calendarMonth="",lastDeletedId=null,toastTimer=null,identityValue="",activeImageLink=null,richSelectionRange=null;
const imageUrlCache=new Map();

function escapeHtml(value){return String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char])}
function agendaDateParts(dateKey,index){const[,month,day]=dateKey.split("-").map(Number),weekday="日一二三四五六"[new Date(`${dateKey}T12:00:00`).getDay()],relative=index===0?"今天":index===1?"明天":index===2?"後天":"";return{label:`${month}月${day}日`,weekday,relative,weekend:weekday==="六"||weekday==="日"}}
function emptyMessage(text){return`<div class="empty">${escapeHtml(text)}</div>`}
function formatDateLabel(dateKey){if(!/^\d{4}-\d{2}-\d{2}$/.test(dateKey||""))return"選擇日期";const[year,month,day]=dateKey.split("-").map(Number),weekday="日一二三四五六"[new Date(year,month-1,day,12).getDay()];return`${year}年${month}月${day}日（${weekday}）`}
function setPriority(priority){const value=Content.PRIORITIES.includes(priority)?priority:"someday";els.bulletPriority.value=value;els.priorityPicker.querySelectorAll("[data-priority]").forEach(button=>{const active=button.dataset.priority===value;button.classList.toggle("active",active);button.setAttribute("aria-checked",String(active))})}
function setBulletDate(dateKey){const value=/^\d{4}-\d{2}-\d{2}$/.test(dateKey||"")?dateKey:Content.localDateKey();els.bulletDate.value=value;els.bulletDateButton.textContent=formatDateLabel(value)}
function renderDatePicker(){const selected=els.bulletDate.value||Content.localDateKey(),monthKey=/^\d{4}-\d{2}$/.test(calendarMonth)?calendarMonth:selected.slice(0,7),[year,month]=monthKey.split("-").map(Number),firstDay=new Date(year,month-1,1,12).getDay(),daysInMonth=new Date(year,month,0,12).getDate(),today=Content.localDateKey(),cells=[];calendarMonth=`${year}-${String(month).padStart(2,"0")}`;els.calendarTitle.textContent=`${year}年${month}月`;for(let index=0;index<firstDay;index++)cells.push('<span class="calendar-blank"></span>');for(let day=1;day<=daysInMonth;day++){const dateKey=`${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`,weekday=new Date(year,month-1,day,12).getDay(),classes=["calendar-day",weekday===0||weekday===6?"weekend":"",dateKey===today?"today-date":"",dateKey===selected?"selected":""].filter(Boolean).join(" ");cells.push(`<button type="button" class="${classes}" data-calendar="select" data-date="${dateKey}" aria-label="${formatDateLabel(dateKey)}" ${dateKey===selected?'aria-current="date"':""}>${day}</button>`)}els.calendarGrid.innerHTML=cells.join("")}
function toggleDatePicker(force){const open=force===undefined?els.datePicker.classList.contains("hidden"):force;els.datePicker.classList.toggle("hidden",!open);els.bulletDateButton.setAttribute("aria-expanded",String(open));if(open){calendarMonth=(els.bulletDate.value||Content.localDateKey()).slice(0,7);renderDatePicker()}}
function shiftCalendarMonth(delta){const[year,month]=calendarMonth.split("-").map(Number),date=new Date(year,month-1+delta,1,12);calendarMonth=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}`;renderDatePicker()}
function driveImageId(url){const value=String(url||"");return value.match(/drive\.google\.com\/file\/d\/([^/?#]+)/i)?.[1]||value.match(/[?&]id=([^&#]+)/i)?.[1]||""}
function sanitizeRichHtml(value){const template=document.createElement("template"),allowed=new Set(["A","B","BR","DETAILS","DIV","EM","FONT","I","LI","OL","P","SPAN","STRONG","SUMMARY","U","UL"]);template.innerHTML=String(value||"");template.content.querySelectorAll("script,style,iframe,object,embed,form,input,button,textarea,select,svg,math").forEach(element=>element.remove());[...template.content.querySelectorAll("*")].forEach(element=>{if(!allowed.has(element.tagName)){element.replaceWith(...element.childNodes);return}[...element.attributes].forEach(attribute=>{const name=attribute.name.toLowerCase(),tag=element.tagName;if(name==="open"&&tag==="DETAILS")return;if(name==="href"&&tag==="A"&&/^https?:\/\//i.test(attribute.value))return;if(name==="size"&&tag==="FONT"&&/^[1-7]$/.test(attribute.value))return;if(name==="color"&&tag==="FONT"&&/^#[0-9a-f]{6}$/i.test(attribute.value))return;if(name==="class"&&["outline-body","outline-children"].includes(attribute.value))return;if(name==="style"&&/^(?:(?:font-size|color):\s*(?:[\d.]+(?:px|em|rem|%)|#[0-9a-f]{6});?\s*)+$/i.test(attribute.value))return;element.removeAttribute(attribute.name)});if(element.tagName==="A"&&!/^https?:\/\//i.test(element.getAttribute("href")||""))element.replaceWith(document.createTextNode(element.textContent||""))});return template.innerHTML}
function decorateProjectLinks(container){container.querySelectorAll("a").forEach(link=>{const href=link.getAttribute("href")||"";link.target="_blank";link.rel="noopener noreferrer";const fileId=driveImageId(href);if(fileId){link.classList.add("project-image-link");link.dataset.fileId=fileId;link.title="指向預覽，點擊開啟大圖"}})}
function renderProjectDetails(value){const raw=String(value||"").trim();if(!raw)return"";const rich=raw.startsWith(RICH_DETAILS_MARKER),source=rich?raw.slice(RICH_DETAILS_MARKER.length):global.marked?.parse?global.marked.parse(escapeHtml(raw),{breaks:true}):`<p>${escapeHtml(raw).replace(/\n/g,"<br>")}</p>`,template=document.createElement("template");template.innerHTML=sanitizeRichHtml(source);decorateProjectLinks(template.content);return template.innerHTML}
function loadProjectDetailsEditor(value){const raw=String(value||"").trim(),html=raw.startsWith(RICH_DETAILS_MARKER)?sanitizeRichHtml(raw.slice(RICH_DETAILS_MARKER.length)):renderProjectDetails(raw);els.projectRichEditor.innerHTML=html||'<details open><summary>新項目</summary><div class="outline-body"><p><br></p></div></details>';decorateProjectLinks(els.projectRichEditor);richSelectionRange=null}
function serializeProjectDetails(){const html=sanitizeRichHtml(els.projectRichEditor.innerHTML),template=document.createElement("template");template.innerHTML=html;return template.content.textContent.trim()||template.content.querySelector("a")?`${RICH_DETAILS_MARKER}${html}`:""}
function rememberRichSelection(){const selection=getSelection();if(selection?.rangeCount&&els.projectRichEditor.contains(selection.anchorNode))richSelectionRange=selection.getRangeAt(0).cloneRange()}
function restoreRichSelection(){els.projectRichEditor.focus();if(!richSelectionRange)return;const selection=getSelection();selection.removeAllRanges();selection.addRange(richSelectionRange)}
function currentOutlineBlock(){const selection=getSelection(),node=selection?.anchorNode instanceof Element?selection.anchorNode:selection?.anchorNode?.parentElement;return node?.closest?.("details")||els.projectRichEditor.querySelector("details:last-of-type")}
function focusOutlineSummary(block){const summary=block.querySelector(":scope > summary"),range=document.createRange(),selection=getSelection();range.selectNodeContents(summary);selection.removeAllRanges();selection.addRange(range);summary.focus?.();rememberRichSelection()}
function addOutlineBlock(){restoreRichSelection();const current=currentOutlineBlock(),block=document.createElement("details");block.open=true;block.innerHTML='<summary>新項目</summary><div class="outline-body"><p><br></p></div>';if(current)current.after(block);else els.projectRichEditor.append(block);focusOutlineSummary(block)}
function moveOutlineBlock(direction){restoreRichSelection();const current=currentOutlineBlock();if(!current)return;if(direction==="indent"){const previous=current.previousElementSibling;if(!previous?.matches("details"))return;let children=previous.querySelector(":scope > .outline-children");if(!children){children=document.createElement("div");children.className="outline-children";previous.append(children)}children.append(current);previous.open=true}else{const children=current.parentElement;if(!children?.classList.contains("outline-children"))return;const parent=children.parentElement;if(parent?.matches("details"))parent.after(current);if(!children.children.length)children.remove()}focusOutlineSummary(current)}
function applyRichCommand(command,value=null){restoreRichSelection();document.execCommand("styleWithCSS",false,false);document.execCommand(command,false,value);rememberRichSelection()}
function insertProjectImageLink(name,url){restoreRichSelection();const selection=getSelection(),range=selection?.rangeCount?selection.getRangeAt(0):null,paragraph=document.createElement("p"),link=document.createElement("a"),fileId=driveImageId(url);link.href=url;link.textContent=`圖片：${name}`;if(fileId){link.className="project-image-link";link.dataset.fileId=fileId;link.title="指向預覽，點擊開啟大圖"}paragraph.append(link);if(range&&els.projectRichEditor.contains(range.commonAncestorContainer)){range.deleteContents();range.insertNode(paragraph);range.setStartAfter(paragraph);range.collapse(true);selection.removeAllRanges();selection.addRange(range)}else els.projectRichEditor.append(paragraph);rememberRichSelection()}
async function getDriveImageUrl(fileId){if(imageUrlCache.has(fileId))return imageUrlCache.get(fileId);const blob=await sync.fetchDriveImage(fileId),url=URL.createObjectURL(blob);imageUrlCache.set(fileId,url);return url}
function positionImageHover(link){const rect=link.getBoundingClientRect(),width=240,left=Math.max(8,Math.min(innerWidth-width-8,rect.left)),above=rect.top>210,top=above?rect.top-198:rect.bottom+8;els.imageHover.style.left=`${left}px`;els.imageHover.style.top=`${Math.max(8,top)}px`}
async function showImageHover(link){activeImageLink=link;els.imageHover.innerHTML='<span class="muted">載入預覽中…</span>';els.imageHover.classList.remove("hidden");positionImageHover(link);try{const url=await getDriveImageUrl(link.dataset.fileId);if(activeImageLink!==link)return;const image=document.createElement("img");image.src=url;image.alt=link.textContent||"專案圖片";els.imageHover.replaceChildren(image);positionImageHover(link)}catch(error){if(activeImageLink===link)els.imageHover.innerHTML='<span class="muted">連接 Google 後可預覽圖片</span>'}}
function hideImageHover(){activeImageLink=null;els.imageHover.classList.add("hidden")}
async function openProjectImage(link){hideImageHover();try{els.imageDialogTitle.textContent=link.textContent||"圖片預覽";els.imageDialogImg.removeAttribute("src");els.imageDialog.showModal();const url=await getDriveImageUrl(link.dataset.fileId);els.imageDialogImg.src=url}catch(error){if(els.imageDialog.open)els.imageDialog.close();sync.reportStatus(error.message==="AUTH_EXPIRED"?"請重新連接 Google 後查看圖片":`圖片載入失敗：${error.message}`,"err")}}

function renderBullet(bullet){
 const done=bullet.status==="done",migrated=bullet.status==="migrated",resolved=migrated&&bullet.chainResolved;
 const classes=["bullet",bullet.priority,done?"done":"",resolved?"resolved":""].filter(Boolean).join(" ");
 const status=migrated?`<span class="migrated-tag">${resolved?"已完成":"已順延"}</span>`:`<button class="status-btn ${done?"checked":""}" data-action="toggle" data-id="${escapeHtml(bullet.id)}" aria-label="${done?"標示為未完成":"標示為完成"}">${done?"✓":""}</button>`;
 const projectAction=bullet.kind==="project",title=projectAction?bullet.title:bullet.action||bullet.title,subtitle=projectAction?`<span class="bullet-action">${escapeHtml(bullet.action||"尚未填寫 Action")}</span>`:"";
 return`<article class="${classes}" data-id="${escapeHtml(bullet.id)}">${status}<button class="bullet-main" data-action="open" data-id="${escapeHtml(bullet.id)}"><span class="bullet-title">${escapeHtml(title)}</span>${subtitle}</button>${migrated?"":`<span class="priority-label">${projectAction?"專案 · ":""}${priorityNames[bullet.priority]}</span>`}</article>`
}

function renderList(bullets,emptyText){return bullets.length?bullets.map(bullet=>renderBullet(bullet)).join(""):emptyMessage(emptyText)}

function renderRollover(candidates){
 const visible=selectedDate===Content.localDateKey()&&candidates.length>0;
 els.rolloverPanel.classList.toggle("hidden",!visible);
 if(!visible)return;
 els.rolloverSummary.textContent=`共有 ${candidates.length} 個之前未完成的 Action，可移到今天。`;
 els.rolloverList.innerHTML=candidates.map(bullet=>`<label class="rollover-row ${escapeHtml(bullet.priority)}"><input type="checkbox" value="${escapeHtml(bullet.id)}" checked><span class="rollover-copy"><strong>${escapeHtml(bullet.action||bullet.title)}</strong>${bullet.kind==="project"?`<span class="bullet-action">專案：${escapeHtml(bullet.title)}</span>`:""}</span><span class="priority-label rollover-priority">${escapeHtml(priorityNames[bullet.priority])}</span></label>`).join("");
}

function renderAgenda(days){
 els.agenda.innerHTML=days.map((day,index)=>{const date=agendaDateParts(day.date,index),dayClass=[index===0?"today-day":"",index===1?"tomorrow-day":"",date.weekend?"weekend":""].filter(Boolean).join(" "),doneSection=day.done.length?`<details class="agenda-section agenda-done" ${index===0?"open":""}><summary class="agenda-section-head"><h3>Done</h3><span class="count">${day.done.length}</span></summary><div class="bullet-list">${renderList(day.done,"尚未完成項目")}</div></details>`:"";return`<section class="panel agenda-day ${dayClass}" data-date="${day.date}"><header class="agenda-date"><time datetime="${day.date}"><span>${date.label}</span><span>（${date.weekday}）</span>${date.relative?`<strong>${date.relative}</strong>`:""}</time></header><div class="agenda-section"><div class="bullet-list">${renderList(day.todo,index===0?"今天沒有待辦事項。":"這天尚未安排待辦事項。")}</div></div>${doneSection}</section>`}).join("")
}

function renderProjects(){
 const projects=Content.getProjects(els.editor.value);
 els.projectsList.innerHTML=projects.length?projects.map(project=>{const details=renderProjectDetails(project.details),actions=project.actions.map(action=>`<li><button class="project-action-row ${action.status==="done"?"done":""}" data-action="open-project" data-id="${escapeHtml(action.id)}"><time datetime="${action.date}">${escapeHtml(action.date)}</time><span class="action-text"><span class="action-priority ${escapeHtml(action.priority)}"></span>${escapeHtml(action.action||"尚未填寫 Action")}</span><span class="action-state">${action.status==="done"?"已完成":"未完成"}</span></button></li>`).join("");return`<article id="project-${escapeHtml(project.id)}" class="panel project-card ${project.projectStatus==="closed"?"closed":""}"><div class="project-card-head"><div class="project-overview"><div class="project-title-row"><strong class="project-title">${escapeHtml(project.title)}</strong><span class="project-badge">${project.projectStatus==="closed"?"已結案":"進行中"}</span></div></div><div class="project-actions"><button class="btn primary" data-action="new-project-action" data-item-id="${escapeHtml(project.id)}" ${project.projectStatus==="closed"?"disabled":""}>新增 Action</button><button class="btn" data-action="edit-project" data-item-id="${escapeHtml(project.id)}">編輯專案</button><button class="btn" data-action="project-status" data-item-id="${escapeHtml(project.id)}" data-status="${project.projectStatus==="closed"?"open":"closed"}">${project.projectStatus==="closed"?"重新開啟":"結案"}</button></div></div><section class="project-content-section"><h3>專案內容</h3>${details?`<div class="project-details-render">${details}</div>`:emptyMessage("尚未填寫專案內容")}</section><section class="project-action-section"><h3>Action List（${project.actions.length}）</h3>${actions?`<ul class="project-action-list">${actions}</ul>`:emptyMessage("尚無 Action")}</section></article>`}).join(""):emptyMessage("還沒有專案。可將一般 Action 轉為專案 Action。");
}

function renderJournal(){
 selectedDate=Content.localDateKey();const view=Content.getViewModel(els.editor.value,selectedDate);
 renderRollover(view.carryCandidates);renderAgenda(Content.getAgenda(els.editor.value,selectedDate,8));
}

function renderDebug(){
 const view=Content.toViewModel(els.editor.value),state=view.debugState,legacy=view.categories[0].items[0].content;
 const markdown=global.marked?.parse?global.marked.parse(legacy):`<pre>${escapeHtml(legacy)}</pre>`;
 els.preview.innerHTML=`<section class="state-lab"><div class="state-lab-head"><div><h4>跨裝置狀態測試</h4><span class="muted">每次操作都會寫進同一份 Drive 文件</span></div><span class="state-sync-badge">文件內狀態</span></div><div class="state-grid"><div class="state-field"><span class="state-label">Checkbox</span><label class="state-check"><input data-debug="checked" type="checkbox" ${state.checked?"checked":""}> 已確認</label></div><div class="state-field"><span class="state-label">Switch</span><label class="state-switch"><input data-debug="switchOn" type="checkbox" ${state.switchOn?"checked":""}><span class="state-switch-track"></span><span>${state.switchOn?"開":"關"}</span></label></div><div class="state-field"><span class="state-label">重要度</span><div class="state-options">${["low","normal","high"].map(value=>`<input id="priority-${value}" data-debug="priority" type="radio" name="priority" value="${value}" ${state.priority===value?"checked":""}><label for="priority-${value}">${{low:"低",normal:"中",high:"高"}[value]}</label>`).join("")}</div></div><div class="state-field"><label for="debug-stage">階段</label><select id="debug-stage" data-debug="stage">${[["todo","待辦"],["doing","進行中"],["waiting","等待"],["done","完成"]].map(([value,label])=>`<option value="${value}" ${state.stage===value?"selected":""}>${label}</option>`).join("")}</select></div><div class="state-field"><span class="state-label">進度</span><div class="state-range"><input data-debug="progress" type="range" min="0" max="100" value="${state.progress}"><output>${state.progress}%</output></div></div><div class="state-field"><label for="debug-note">短文字</label><input id="debug-note" data-debug="note" type="text" maxlength="80" value="${escapeHtml(state.note)}" placeholder="跨裝置同步內容"></div></div></section>${markdown}`;
}

function renderAll(){renderJournal();renderProjects();renderDebug()}
function backupLegacyOnce(){const parsed=Content.parse(els.editor.value);if(parsed.hasJournal)return;try{const scope=(els.fileId.value.trim()||"local").replace(/[^a-zA-Z0-9_-]/g,"_");localStorage.setItem(`driveMemoV1Backup:${scope}:${Date.now()}`,els.editor.value)}catch{}}
function mutateContent(producer,{journal=true}={}){if(journal)backupLegacyOnce();const next=producer(els.editor.value);if(typeof next!=="string"||next===els.editor.value)return;els.editor.value=next;renderAll();sync.localContentChanged()}

function openBulletDialog(id="",projectId="",editProject=false){
 const bullet=id?Content.getBullet(els.editor.value,id):null;
 const projectItem=projectId?Content.getProjects(els.editor.value).find(value=>value.id===projectId):null,history=bullet?Content.getItemHistory(els.editor.value,id):[],project=bullet?.kind==="project"||Boolean(projectItem),newProjectAction=!bullet&&projectItem&&!editProject,details=bullet?.details||projectItem?.details||"";els.bulletMode.value=editProject?"project":"action";els.bulletDialogTitle.textContent=editProject?"編輯專案":bullet?project?"編輯專案 Action":"編輯 Action":project?"新增專案 Action":"新增 Action";els.bulletId.value=bullet?.id||"";els.bulletProjectId.value=project?(bullet?.itemId||projectItem.id):"";els.projectNameField.classList.toggle("hidden",!project);els.projectNameField.querySelector("label").textContent=editProject?"專案名稱":"所屬專案";els.bulletTitle.value=project?(bullet?.title||projectItem.title):"";els.bulletTitle.readOnly=Boolean(newProjectAction);els.actionField.classList.toggle("hidden",editProject);els.actionDateField.classList.toggle("hidden",editProject);els.actionPriorityField.classList.toggle("hidden",editProject);els.bulletAction.required=!editProject;els.bulletAction.value=editProject?"":bullet?.action||(!project&&bullet?.title)||"";setBulletDate(bullet?.date||selectedDate);setPriority(bullet?.priority||"someday");els.bulletDetails.value=project?"":details;els.bulletDetails.classList.toggle("hidden",project);els.projectRichEditor.classList.toggle("hidden",!project);if(project)loadProjectDetailsEditor(details);else els.projectRichEditor.replaceChildren();els.bulletDetailsLabel.textContent=editProject?"專案內容":project?"專案內容（所有專案 Action 共用）":"Action 細節";els.goToProjectBtn.classList.toggle("hidden",!bullet||bullet.kind!=="project");els.goToProjectBtn.dataset.itemId=project?(bullet?.itemId||projectItem?.id||""):"";els.projectDetailsTools.classList.toggle("hidden",!project);els.deleteBulletBtn.classList.toggle("hidden",!bullet||editProject);els.convertProjectBtn.classList.toggle("hidden",!bullet||project||editProject);els.bulletHistoryField.classList.toggle("hidden",!bullet||editProject);els.bulletHistory.innerHTML=history.map(entry=>`<div class="history-row"><time>${escapeHtml(entry.date)}</time><span class="history-action">${escapeHtml(entry.action)}</span><span class="history-state">${entry.status==="done"?"已完成":entry.status==="migrated"?"舊順延紀錄":"未完成"}</span></div>`).join("");toggleDatePicker(false);els.bulletDialog.showModal();setTimeout(()=>(editProject?els.bulletTitle:els.bulletAction).focus(),0)
}
function closeBulletDialog(){els.bulletDialog.close()}
function showToast(text,id){lastDeletedId=id;els.toastText.textContent=text;els.toast.classList.remove("hidden");clearTimeout(toastTimer);toastTimer=setTimeout(()=>{els.toast.classList.add("hidden");lastDeletedId=null},6000)}

function handleJournalClick(event){
 const target=event.target.closest("[data-action]");if(!target)return;const id=target.dataset.id;
 if(target.dataset.action==="open")openBulletDialog(id);
 if(target.dataset.action==="toggle"){const bullet=Content.getBullet(els.editor.value,id);if(bullet)mutateContent(markdown=>Content.setBulletStatus(markdown,id,bullet.status==="done"?"todo":"done"))}
}

function handleProjectsClick(event){const target=event.target.closest("[data-action]");if(!target)return;if(target.dataset.action==="open-project"&&target.dataset.id)openBulletDialog(target.dataset.id);if(target.dataset.action==="new-project-action")openBulletDialog("",target.dataset.itemId);if(target.dataset.action==="edit-project")openBulletDialog("",target.dataset.itemId,true);if(target.dataset.action==="project-status")mutateContent(markdown=>Content.setProjectStatus(markdown,target.dataset.itemId,target.dataset.status))}

function carrySelected(all=false){const ids=all?[...els.rolloverList.querySelectorAll("input")].map(input=>input.value):[...els.rolloverList.querySelectorAll("input:checked")].map(input=>input.value);if(!ids.length){sync.reportStatus("請先勾選要順延的項目","");return}mutateContent(markdown=>Content.carryForward(markdown,ids,Content.localDateKey()))}

function route(){const page=location.hash==="#projects"?"projects":location.hash==="#sync-debug"?"debug":"journal";els.journalPage.classList.toggle("hidden",page!=="journal");els.projectsPage.classList.toggle("hidden",page!=="projects");els.debugPage.classList.toggle("hidden",page!=="debug");els.journalNav.classList.toggle("active",page==="journal");els.projectsNav.classList.toggle("active",page==="projects");els.debugNav.classList.toggle("active",page==="debug")}
function setStatus(text,kind=""){els.statusText.textContent=text;els.stateDot.className=`dot ${kind}`.trim()}
function setConnected(connected){els.loginBtn.disabled=connected;els.logoutBtn.disabled=!connected;els.openBtn.disabled=!connected;els.syncBtn.disabled=!connected}
function setIdentity(value){identityValue=value;els.identity.textContent=value}
function setMeta(meta){els.fileMeta.textContent=meta?.name?`${meta.name} · v${meta.version||"?"}`:""}
function setDirty(dirty){els.dirtyState.textContent=dirty?"有尚未同步的修改":""}

function diffSummary(local,cloud){
 if(!global.Diff?.diffLines)return"本機與雲端內容不同，請選擇保留哪一版。";
 return global.Diff.diffLines(cloud,local).slice(0,80).map(part=>`<div class="${part.added?"diff-add":part.removed?"diff-del":"diff-same"}">${escapeHtml(part.value)}</div>`).join("")
}
function showConflict(data){els.diffView.innerHTML=diffSummary(data.localContent,data.cloudContent);els.localConflict.textContent=data.localContent;els.cloudConflict.textContent=data.cloudContent;els.conflictDialog.showModal()}
function closeConflict(){if(els.conflictDialog.open)els.conflictDialog.close()}

const sync=global.DriveMemoSync.create({
 config:global.APP_CONFIG||{},getFileId:()=>els.fileId.value,getLocalContent:()=>els.editor.value,getIdentity:()=>identityValue,
 applyContent:content=>{els.editor.value=content;renderAll()},onStatus:setStatus,onDirty:setDirty,onMeta:setMeta,onIdentity:setIdentity,onConnected:setConnected,onConflict:showConflict,onConflictResolved:closeConflict
});

function bindEvents(){
 addEventListener("hashchange",route);
 els.addBulletBtn.addEventListener("click",()=>openBulletDialog());els.journalPage.addEventListener("click",handleJournalClick);els.projectsPage.addEventListener("click",handleProjectsClick);els.rolloverSelectedBtn.addEventListener("click",()=>carrySelected(false));els.rolloverAllBtn.addEventListener("click",()=>carrySelected(true));
 els.priorityPicker.addEventListener("click",event=>{const button=event.target.closest("[data-priority]");if(button)setPriority(button.dataset.priority)});els.bulletDateButton.addEventListener("click",()=>toggleDatePicker());els.datePicker.addEventListener("click",event=>{const target=event.target.closest("[data-calendar]");if(!target)return;if(target.dataset.calendar==="previous")shiftCalendarMonth(-1);if(target.dataset.calendar==="next")shiftCalendarMonth(1);if(target.dataset.calendar==="select"){setBulletDate(target.dataset.date);toggleDatePicker(false)}});
 els.projectRichEditor.addEventListener("keyup",rememberRichSelection);els.projectRichEditor.addEventListener("mouseup",rememberRichSelection);els.projectRichEditor.addEventListener("focus",rememberRichSelection);els.projectRichEditor.addEventListener("keydown",event=>{const selection=getSelection(),node=selection?.anchorNode instanceof Element?selection.anchorNode:selection?.anchorNode?.parentElement;if(event.key==="Tab"){event.preventDefault();moveOutlineBlock(event.shiftKey?"outdent":"indent")}else if(event.key==="Enter"&&!event.shiftKey&&node?.closest("summary")){event.preventDefault();addOutlineBlock()}});els.projectDetailsTools.addEventListener("mousedown",event=>{if(event.target.closest("button")){rememberRichSelection();event.preventDefault()}});els.projectDetailsTools.addEventListener("click",event=>{const tool=event.target.closest("[data-detail-tool]")?.dataset.detailTool;if(tool==="add-block")addOutlineBlock();if(tool==="indent"||tool==="outdent")moveOutlineBlock(tool);if(tool==="bold")applyRichCommand("bold")});els.projectTextSize.addEventListener("change",()=>applyRichCommand("fontSize",els.projectTextSize.value));els.projectTextColor.addEventListener("input",()=>applyRichCommand("foreColor",els.projectTextColor.value));els.projectImageBtn.addEventListener("click",()=>{rememberRichSelection();els.projectImageInput.click()});els.projectImageInput.addEventListener("change",async()=>{const file=els.projectImageInput.files?.[0],projectId=els.bulletProjectId.value,project=Content.getProjects(els.editor.value).find(value=>value.id===projectId);if(!file||!project)return;const oldText=els.projectImageBtn.textContent;els.projectImageBtn.disabled=true;els.projectImageBtn.textContent="上傳中…";sync.reportStatus("正在上傳專案圖片…","sync");try{const uploaded=await sync.uploadProjectImage({file,projectId,projectTitle:project.title}),name=String(uploaded.name||file.name).replace(/[\[\]]/g,"");insertProjectImageLink(name,uploaded.url);sync.reportStatus("圖片已上傳，連結已插入專案內容","ok")}catch(error){if(error.message!=="AUTH_EXPIRED")sync.reportStatus(`圖片上傳失敗：${error.message}`,"err")}finally{els.projectImageInput.value="";els.projectImageBtn.disabled=false;els.projectImageBtn.textContent=oldText}});
 document.addEventListener("mouseover",event=>{const link=event.target.closest?.(".project-image-link");if(link&&!link.contains(event.relatedTarget))showImageHover(link)});document.addEventListener("mouseout",event=>{const link=event.target.closest?.(".project-image-link");if(link&&!link.contains(event.relatedTarget))hideImageHover()});document.addEventListener("click",event=>{const link=event.target.closest?.(".project-image-link");if(link){event.preventDefault();openProjectImage(link)}});els.closeImageBtn.addEventListener("click",()=>els.imageDialog.close());els.imageDialog.addEventListener("click",event=>{if(event.target===els.imageDialog)els.imageDialog.close()});addEventListener("beforeunload",()=>imageUrlCache.forEach(url=>URL.revokeObjectURL(url)));
 els.goToProjectBtn.addEventListener("click",()=>{const itemId=els.goToProjectBtn.dataset.itemId;if(!itemId)return;closeBulletDialog();location.hash="#projects";setTimeout(()=>document.getElementById(`project-${itemId}`)?.scrollIntoView({behavior:"smooth",block:"start"}),0)});els.cancelBulletBtn.addEventListener("click",closeBulletDialog);els.bulletForm.addEventListener("submit",event=>{event.preventDefault();const action=els.bulletAction.value.trim(),projectId=els.bulletProjectId.value,data={title:projectId?els.bulletTitle.value.trim():action,action,date:els.bulletDate.value,priority:els.bulletPriority.value,details:projectId?serializeProjectDetails():els.bulletDetails.value.trim()};if(els.bulletMode.value==="project"){if(!projectId||!data.title)return;mutateContent(markdown=>Content.updateProject(markdown,projectId,{title:data.title,details:data.details}));closeBulletDialog();return}if(!data.action||projectId&&!data.title)return;const id=els.bulletId.value;mutateContent(markdown=>id?Content.updateBullet(markdown,id,data):projectId?Content.addProjectAction(markdown,projectId,data).markdown:Content.addBullet(markdown,data).markdown);closeBulletDialog()});
 els.convertProjectBtn.addEventListener("click",()=>{if(!els.bulletId.value||!els.bulletAction.value.trim())return;els.convertProjectName.value=els.bulletAction.value.trim();els.convertDialog.showModal();setTimeout(()=>els.convertProjectName.select(),0)});els.cancelConvertBtn.addEventListener("click",()=>els.convertDialog.close());els.convertForm.addEventListener("submit",event=>{event.preventDefault();const id=els.bulletId.value,projectName=els.convertProjectName.value.trim(),action=els.bulletAction.value.trim();if(!id||!projectName||!action)return;const data={title:projectName,action,date:els.bulletDate.value,priority:els.bulletPriority.value,details:els.bulletDetails.value.trim()};mutateContent(markdown=>Content.convertToProject(Content.updateBullet(markdown,id,data),id));els.convertDialog.close();closeBulletDialog();location.hash="#projects"});
 els.deleteBulletBtn.addEventListener("click",()=>{const id=els.bulletId.value,title=els.bulletAction.value.trim()||"Action";if(!id)return;mutateContent(markdown=>Content.softDeleteBullet(markdown,id));closeBulletDialog();showToast(`已刪除 Action「${title}」`,id)});els.undoDeleteBtn.addEventListener("click",()=>{if(!lastDeletedId)return;mutateContent(markdown=>Content.restoreBullet(markdown,lastDeletedId));lastDeletedId=null;els.toast.classList.add("hidden")});
 els.preview.addEventListener("change",event=>{const key=event.target.dataset.debug;if(!key)return;let value=event.target.value;if(event.target.type==="checkbox")value=event.target.checked;if(event.target.type==="range")value=Number(value);mutateContent(markdown=>Content.updateDebugState(markdown,{[key]:value}),{journal:false})});els.preview.addEventListener("input",event=>{if(event.target.dataset.debug==="progress")event.target.nextElementSibling.value=`${event.target.value}%`});
 els.editor.addEventListener("input",()=>{renderAll();sync.localContentChanged()});els.fileId.addEventListener("change",()=>sync.fileIdChanged());els.loginBtn.addEventListener("click",()=>sync.requestLogin());els.logoutBtn.addEventListener("click",()=>sync.logout());els.openBtn.addEventListener("click",()=>sync.openCurrentFile());els.syncBtn.addEventListener("click",()=>sync.syncCheck());
 els.laterBtn.addEventListener("click",()=>{sync.resolveLater();closeConflict()});els.cloudBtn.addEventListener("click",()=>sync.resolveUseCloud());els.localBtn.addEventListener("click",()=>sync.resolveKeepLocal());
}

function initialize(){els.fileId.value=localStorage.getItem("driveMemoFileId")||"";bindEvents();route();renderAll();sync.initialize().catch(error=>setStatus(`初始化失敗：${error.message}`,"err"));if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})}

initialize();
global.DriveMemoUI=Object.freeze({renderAll,sync});
})(window);
