const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
function harness({ready=false,failed=false,storageBlocked=false,delay=0,online=true}={}){
 let tick=0,clients=0,popups=0,appends=0,callback,errorCallback,now=Date.now();const status=[],listeners={},values=new Map(),script={dataset:{failed:String(failed)},remove(){}};
 const win={navigator:{onLine:online},addEventListener(type,handler){listeners[type]=handler}},sdk={accounts:{oauth2:{initTokenClient(opts){clients++;callback=opts.callback;errorCallback=opts.error_callback;return {requestAccessToken(){popups++}}},revoke(){}}}};if(ready)win.google=sdk;
 const storage={getItem(key){if(storageBlocked)throw Error('SecurityError');return values.get(key)??null},setItem(key,value){if(storageBlocked)throw Error('SecurityError');values.set(key,String(value))},removeItem(key){if(storageBlocked)throw Error('SecurityError');values.delete(key)}};
 const context={window:win,document:{getElementById:()=>script,createElement:()=>({dataset:{}}),head:{append(){appends++;script.dataset.failed='false'}},hidden:false},sessionStorage:storage,localStorage:storage,Headers,Date,URLSearchParams,Blob,setTimeout(fn){tick++;if(delay&&tick>=delay)win.google=sdk;queueMicrotask(fn)},clearTimeout(){},setInterval(){},clearInterval(){},fetch:async()=>({ok:true,status:200,json:async()=>({email:'test@example.com'})})};
 context.Date=class extends Date{static now(){return now}};
 vm.createContext(context);vm.runInContext(fs.readFileSync('sync.js','utf8'),context);const sync=win.DriveMemoSync.create({config:{GOOGLE_CLIENT_ID:'test-client'},onStatus:text=>status.push(text)});
 return {sync,status,win,sdk,get clients(){return clients},get popups(){return popups},get appends(){return appends},advance:ms=>now+=ms,setOnline(value){win.navigator.onLine=value},fire:type=>listeners[type]?.(),cancel:()=>errorCallback({type:'popup_closed'}),authorize:(expires=3600)=>callback({access_token:'fake-test-token',expires_in:expires})};
}
(async()=>{
 const reload=harness({ready:true});await reload.sync.initialize();assert.equal(reload.popups,1);await reload.authorize();assert(reload.status.includes('已自動登入 Google'));console.log('PASS refresh automatically restores Google login');
 const slow=harness({delay:80});await slow.sync.initialize();assert.equal(slow.clients,1);slow.sync.requestLogin();assert.equal(slow.popups,1);console.log('PASS SDK loading longer than old six-second limit');
 const blocked=harness({ready:true,storageBlocked:true});await blocked.sync.initialize();blocked.sync.requestLogin();await blocked.authorize();assert.equal(blocked.popups,1);assert(blocked.status.includes('Google 已連接'));console.log('PASS restricted session storage does not break initialization or login');
 const retry=harness({failed:true,delay:3});await retry.sync.initialize();assert(retry.status.at(-1).includes('載入失敗'));await retry.sync.requestLogin();assert.equal(retry.appends,1);assert.equal(retry.popups,0);assert(retry.status.at(-1).includes('再點一次'));retry.sync.requestLogin();assert.equal(retry.popups,1);console.log('PASS failed load retry; popup only opens on next direct click');
 const timeout=harness();await timeout.sync.initialize();assert(timeout.status.at(-1).includes('逾時'));timeout.win.google=timeout.sdk;timeout.sync.requestLogin();assert.equal(timeout.popups,1);console.log('PASS late SDK after timeout recovers on login click');
 const concurrent=harness({delay:10});await Promise.all([concurrent.sync.initialize(),concurrent.sync.requestLogin(),concurrent.sync.requestLogin()]);assert.equal(concurrent.clients,1);assert.equal(concurrent.popups,1);console.log('PASS concurrent readiness requests share one initialization and one automatic login');
 const renewal=harness({ready:true});await renewal.sync.initialize();renewal.sync.requestLogin();await renewal.authorize(60);const before=renewal.popups;renewal.sync.userActivity();assert.equal(renewal.popups,before+1);await renewal.authorize();assert(renewal.status.includes('Google 連線已延長'));console.log('PASS active session renews an expiring Google token');
 const cancelled=harness({ready:true});await cancelled.sync.initialize();cancelled.sync.requestLogin();await cancelled.authorize(600);cancelled.sync.userActivity();const attempts=cancelled.popups;cancelled.sync.requestLogin();assert.equal(cancelled.popups,attempts);cancelled.cancel();cancelled.advance(120000);cancelled.sync.userActivity();assert.equal(cancelled.popups,attempts);cancelled.sync.requestLogin();assert.equal(cancelled.popups,attempts+1);await cancelled.authorize();console.log('PASS cancelled renewal stays quiet and explicit reconnect remains available');
 const reconnect=harness({ready:true,online:false});await reconnect.sync.initialize();assert.equal(reconnect.popups,0);reconnect.setOnline(true);reconnect.fire('online');await new Promise(setImmediate);assert.equal(reconnect.popups,1);await reconnect.authorize();assert(reconnect.status.includes('已自動登入 Google'));console.log('PASS reconnect automatically restores Google login');
 const signedOut=harness({ready:true});await signedOut.sync.initialize();await signedOut.authorize();const signedOutAttempts=signedOut.popups;await signedOut.sync.logout();signedOut.setOnline(false);signedOut.fire('offline');signedOut.setOnline(true);signedOut.fire('online');await signedOut.sync.initialize();assert.equal(signedOut.popups,signedOutAttempts);console.log('PASS explicit logout prevents automatic login after reconnect or refresh');
})().catch(e=>{console.error(e);process.exitCode=1});
