const assert=require('node:assert/strict');
require('../reminder-test.js');
const {buildTransfer,localInput}=globalThis.DriveMemoReminderTest;
const local='2030-09-12T15:07',future=new Date(local),now=future.getTime()-300000;
const title='聯絡 Shawn & 客戶 + #測試 "提醒" 🔔';
const result=buildTransfer(title,local,now),url=new URL(result.url);
assert.equal(url.protocol,'shortcuts:');
assert.equal(url.hostname,'run-shortcut');
assert.equal(url.searchParams.get('name'),'Drive Memo 提醒測試');
assert.equal(url.searchParams.get('input'),'text');
const data=JSON.parse(url.searchParams.get('text'));
assert.equal(data.title,title);
assert.equal(Date.parse(data.dueAt),future.getTime());
assert.equal(localInput(new Date(data.dueAt)),local);
assert.deepEqual(Object.keys(data),['title','dueAt']);
assert.throws(()=>buildTransfer(' ',local,now),/標題/);
assert.throws(()=>buildTransfer('x'.repeat(161),local,now),/標題/);
for(const value of ['','2030-09-12','2030-02-30T10:00','2030-13-01T10:00','2030-09-12T25:01'])assert.throws(()=>buildTransfer(title,value,now));
assert.throws(()=>buildTransfer(title,local,future.getTime()),/已過/);
assert.throws(()=>buildTransfer(title,local,future.getTime()+1),/已過/);
console.log('PASS shortcut Unicode payload, local/UTC round trip, no credentials, invalid and elapsed dates');
